// Generated by rstantools.  Do not edit by hand.

/*
    qc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    qc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with qc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_t_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 219> locations_array__ =
  {" (found before start of program)",
  " (in 't', line 217, column 2 to column 138)",
  " (in 't', line 218, column 2 to column 141)",
  " (in 't', line 219, column 2 to column 138)",
  " (in 't', line 222, column 2 to column 10)",
  " (in 't', line 223, column 2 to column 13)",
  " (in 't', line 224, column 2 to column 10)",
  " (in 't', line 228, column 4 to column 21)",
  " (in 't', line 227, column 9 to line 229, column 3)",
  " (in 't', line 226, column 4 to column 23)",
  " (in 't', line 225, column 24 to line 227, column 3)",
  " (in 't', line 225, column 2 to line 229, column 3)",
  " (in 't', line 233, column 4 to column 21)",
  " (in 't', line 232, column 9 to line 234, column 3)",
  " (in 't', line 231, column 4 to column 19)",
  " (in 't', line 230, column 24 to line 232, column 3)",
  " (in 't', line 230, column 2 to line 234, column 3)",
  " (in 't', line 238, column 4 to column 51)",
  " (in 't', line 237, column 9 to line 239, column 3)",
  " (in 't', line 236, column 4 to column 49)",
  " (in 't', line 235, column 27 to line 237, column 3)",
  " (in 't', line 235, column 2 to line 239, column 3)",
  " (in 't', line 243, column 27 to column 137)",
  " (in 't', line 243, column 2 to column 137)",
  " (in 't', line 244, column 27 to column 140)",
  " (in 't', line 244, column 2 to column 140)",
  " (in 't', line 245, column 27 to column 137)",
  " (in 't', line 245, column 2 to column 137)",
  " (in 't', line 247, column 26 to column 70)",
  " (in 't', line 247, column 2 to column 70)",
  " (in 't', line 189, column 2 to column 17)",
  " (in 't', line 191, column 9 to column 10)",
  " (in 't', line 191, column 2 to column 14)",
  " (in 't', line 193, column 2 to column 18)",
  " (in 't', line 194, column 2 to column 21)",
  " (in 't', line 195, column 2 to column 18)",
  " (in 't', line 197, column 9 to column 36)",
  " (in 't', line 197, column 2 to column 48)",
  " (in 't', line 198, column 9 to column 36)",
  " (in 't', line 198, column 2 to column 51)",
  " (in 't', line 199, column 9 to column 36)",
  " (in 't', line 199, column 2 to column 48)",
  " (in 't', line 200, column 8 to column 35)",
  " (in 't', line 200, column 2 to column 56)",
  " (in 't', line 201, column 8 to column 35)",
  " (in 't', line 201, column 2 to column 59)",
  " (in 't', line 202, column 8 to column 35)",
  " (in 't', line 202, column 2 to column 56)",
  " (in 't', line 204, column 8 to column 35)",
  " (in 't', line 204, column 2 to column 51)",
  " (in 't', line 205, column 8 to column 35)",
  " (in 't', line 205, column 2 to column 54)",
  " (in 't', line 206, column 8 to column 35)",
  " (in 't', line 206, column 2 to column 51)",
  " (in 't', line 208, column 9 to column 36)",
  " (in 't', line 208, column 2 to column 58)",
  " (in 't', line 209, column 9 to column 36)",
  " (in 't', line 209, column 2 to column 61)",
  " (in 't', line 210, column 9 to column 36)",
  " (in 't', line 210, column 2 to column 58)",
  " (in 't', line 211, column 2 to column 20)",
  " (in 't', line 212, column 2 to column 23)",
  " (in 't', line 213, column 2 to column 20)",
  " (in 't', line 214, column 2 to column 20)",
  " (in 't', line 217, column 8 to column 19)",
  " (in 't', line 218, column 8 to column 22)",
  " (in 't', line 219, column 8 to column 19)",
  " (in 't', line 6, column 4 to column 13)",
  " (in 't', line 5, column 32 to line 7, column 3)",
  " (in 't', line 9, column 4 to column 24)",
  " (in 't', line 8, column 38 to line 10, column 3)",
  " (in 't', line 14, column 4 to column 13)",
  " (in 't', line 15, column 4 to column 15)",
  " (in 't', line 16, column 4 to column 12)",
  " (in 't', line 20, column 6 to column 24)",
  " (in 't', line 21, column 6 to column 26)",
  " (in 't', line 19, column 11 to line 22, column 5)",
  " (in 't', line 18, column 6 to column 33)",
  " (in 't', line 17, column 36 to line 19, column 5)",
  " (in 't', line 17, column 4 to line 22, column 5)",
  " (in 't', line 26, column 6 to column 17)",
  " (in 't', line 24, column 6 to column 31)",
  " (in 't', line 23, column 4 to line 26, column 17)",
  " (in 't', line 27, column 4 to column 14)",
  " (in 't', line 13, column 54 to line 28, column 3)",
  " (in 't', line 30, column 4 to column 13)",
  " (in 't', line 31, column 4 to column 15)",
  " (in 't', line 32, column 4 to column 12)",
  " (in 't', line 36, column 6 to column 24)",
  " (in 't', line 37, column 6 to column 26)",
  " (in 't', line 35, column 11 to line 38, column 5)",
  " (in 't', line 34, column 6 to column 33)",
  " (in 't', line 33, column 36 to line 35, column 5)",
  " (in 't', line 33, column 4 to line 38, column 5)",
  " (in 't', line 42, column 6 to column 17)",
  " (in 't', line 40, column 6 to column 31)",
  " (in 't', line 39, column 4 to line 42, column 17)",
  " (in 't', line 43, column 4 to column 14)",
  " (in 't', line 29, column 54 to line 44, column 3)",
  " (in 't', line 49, column 4 to column 12)",
  " (in 't', line 53, column 6 to column 23)",
  " (in 't', line 51, column 6 to column 31)",
  " (in 't', line 50, column 4 to line 53, column 23)",
  " (in 't', line 54, column 4 to column 14)",
  " (in 't', line 48, column 46 to line 55, column 3)",
  " (in 't', line 57, column 4 to column 12)",
  " (in 't', line 61, column 6 to column 23)",
  " (in 't', line 59, column 6 to column 31)",
  " (in 't', line 58, column 4 to line 61, column 23)",
  " (in 't', line 62, column 4 to column 14)",
  " (in 't', line 56, column 46 to line 63, column 3)",
  " (in 't', line 78, column 4 to column 12)",
  " (in 't', line 181, column 6 to column 42)",
  " (in 't', line 180, column 30 to line 182, column 5)",
  " (in 't', line 180, column 10 to line 182, column 5)",
  " (in 't', line 179, column 6 to column 39)",
  " (in 't', line 178, column 30 to line 180, column 5)",
  " (in 't', line 178, column 10 to line 182, column 5)",
  " (in 't', line 167, column 6 to column 61)",
  " (in 't', line 176, column 8 to column 65)",
  " (in 't', line 175, column 35 to line 177, column 7)",
  " (in 't', line 175, column 12 to line 177, column 7)",
  " (in 't', line 174, column 8 to column 65)",
  " (in 't', line 173, column 35 to line 175, column 7)",
  " (in 't', line 173, column 12 to line 177, column 7)",
  " (in 't', line 169, column 8 to line 172, column 10)",
  " (in 't', line 168, column 52 to line 173, column 7)",
  " (in 't', line 168, column 6 to line 177, column 7)",
  " (in 't', line 166, column 29 to line 178, column 5)",
  " (in 't', line 166, column 10 to line 182, column 5)",
  " (in 't', line 155, column 6 to column 75)",
  " (in 't', line 164, column 8 to column 79)",
  " (in 't', line 163, column 35 to line 165, column 7)",
  " (in 't', line 163, column 12 to line 165, column 7)",
  " (in 't', line 162, column 8 to column 79)",
  " (in 't', line 161, column 35 to line 163, column 7)",
  " (in 't', line 161, column 12 to line 165, column 7)",
  " (in 't', line 157, column 8 to line 160, column 10)",
  " (in 't', line 156, column 52 to line 161, column 7)",
  " (in 't', line 156, column 6 to line 165, column 7)",
  " (in 't', line 154, column 29 to line 166, column 5)",
  " (in 't', line 154, column 10 to line 182, column 5)",
  " (in 't', line 153, column 6 to column 78)",
  " (in 't', line 152, column 29 to line 154, column 5)",
  " (in 't', line 152, column 10 to line 182, column 5)",
  " (in 't', line 141, column 6 to column 80)",
  " (in 't', line 150, column 8 to column 84)",
  " (in 't', line 149, column 35 to line 151, column 7)",
  " (in 't', line 149, column 12 to line 151, column 7)",
  " (in 't', line 148, column 8 to column 84)",
  " (in 't', line 147, column 35 to line 149, column 7)",
  " (in 't', line 147, column 12 to line 151, column 7)",
  " (in 't', line 143, column 8 to line 146, column 10)",
  " (in 't', line 142, column 52 to line 147, column 7)",
  " (in 't', line 142, column 6 to line 151, column 7)",
  " (in 't', line 140, column 29 to line 152, column 5)",
  " (in 't', line 140, column 10 to line 182, column 5)",
  " (in 't', line 129, column 6 to column 76)",
  " (in 't', line 138, column 8 to column 80)",
  " (in 't', line 137, column 35 to line 139, column 7)",
  " (in 't', line 137, column 12 to line 139, column 7)",
  " (in 't', line 136, column 8 to column 80)",
  " (in 't', line 135, column 35 to line 137, column 7)",
  " (in 't', line 135, column 12 to line 139, column 7)",
  " (in 't', line 131, column 8 to line 134, column 10)",
  " (in 't', line 130, column 52 to line 135, column 7)",
  " (in 't', line 130, column 6 to line 139, column 7)",
  " (in 't', line 128, column 29 to line 140, column 5)",
  " (in 't', line 128, column 10 to line 182, column 5)",
  " (in 't', line 117, column 6 to column 101)",
  " (in 't', line 126, column 8 to column 105)",
  " (in 't', line 125, column 35 to line 127, column 7)",
  " (in 't', line 125, column 12 to line 127, column 7)",
  " (in 't', line 124, column 8 to column 105)",
  " (in 't', line 123, column 35 to line 125, column 7)",
  " (in 't', line 123, column 12 to line 127, column 7)",
  " (in 't', line 119, column 8 to line 122, column 10)",
  " (in 't', line 118, column 52 to line 123, column 7)",
  " (in 't', line 118, column 6 to line 127, column 7)",
  " (in 't', line 116, column 29 to line 128, column 5)",
  " (in 't', line 116, column 10 to line 182, column 5)",
  " (in 't', line 105, column 6 to column 77)",
  " (in 't', line 114, column 8 to column 81)",
  " (in 't', line 113, column 35 to line 115, column 7)",
  " (in 't', line 113, column 12 to line 115, column 7)",
  " (in 't', line 112, column 8 to column 81)",
  " (in 't', line 111, column 35 to line 113, column 7)",
  " (in 't', line 111, column 12 to line 115, column 7)",
  " (in 't', line 107, column 8 to line 110, column 10)",
  " (in 't', line 106, column 52 to line 111, column 7)",
  " (in 't', line 106, column 6 to line 115, column 7)",
  " (in 't', line 104, column 29 to line 116, column 5)",
  " (in 't', line 104, column 10 to line 182, column 5)",
  " (in 't', line 93, column 6 to column 80)",
  " (in 't', line 102, column 8 to column 84)",
  " (in 't', line 101, column 35 to line 103, column 7)",
  " (in 't', line 101, column 12 to line 103, column 7)",
  " (in 't', line 100, column 8 to column 84)",
  " (in 't', line 99, column 35 to line 101, column 7)",
  " (in 't', line 99, column 12 to line 103, column 7)",
  " (in 't', line 95, column 8 to line 98, column 10)",
  " (in 't', line 94, column 52 to line 99, column 7)",
  " (in 't', line 94, column 6 to line 103, column 7)",
  " (in 't', line 92, column 29 to line 104, column 5)",
  " (in 't', line 92, column 10 to line 182, column 5)",
  " (in 't', line 81, column 6 to column 77)",
  " (in 't', line 90, column 8 to column 81)",
  " (in 't', line 89, column 35 to line 91, column 7)",
  " (in 't', line 89, column 12 to line 91, column 7)",
  " (in 't', line 88, column 8 to column 81)",
  " (in 't', line 87, column 35 to line 89, column 7)",
  " (in 't', line 87, column 12 to line 91, column 7)",
  " (in 't', line 83, column 8 to line 86, column 10)",
  " (in 't', line 82, column 52 to line 87, column 7)",
  " (in 't', line 82, column 6 to line 91, column 7)",
  " (in 't', line 80, column 23 to line 92, column 5)",
  " (in 't', line 80, column 4 to line 182, column 5)",
  " (in 't', line 184, column 4 to column 14)",
  " (in 't', line 77, column 113 to line 185, column 3)"};
template <bool propto__, typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>* = nullptr>
stan::promote_args_t<T0__>
Jeffreys_mu_lpdf(const T0__& mu, std::ostream* pstream__);
template <bool propto__, typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>* = nullptr>
stan::promote_args_t<T0__>
Jeffreys_sigma_lpdf(const T0__& sigma, std::ostream* pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>>
coefs_lb(const std::vector<int>& type_in, const T1__& bound_in_arg__,
         std::ostream* pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>>
coefs_ub(const std::vector<int>& type_in, const T1__& bound_in_arg__,
         std::ostream* pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>>
data_lb(const int& is_trunc, const T1__& trunc_in_arg__, std::ostream*
        pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>>
data_ub(const int& is_trunc, const T1__& trunc_in_arg__, std::ostream*
        pstream__);
template <typename T0__, typename T2__, typename T4__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>>* = nullptr>
stan::promote_args_t<T0__, stan::base_type_t<T2__>, stan::base_type_t<T4__>>
set_prior(const T0__& parameter, const int& prior_type, const T2__&
          prior_parameters_arg__, const std::vector<int>& bounds_type,
          const T4__& bounds_arg__, std::ostream* pstream__);
template <bool propto__, typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>*>
stan::promote_args_t<T0__>
Jeffreys_mu_lpdf(const T0__& mu, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__>;
  int current_statement__ = 0;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 67;
    return 0;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <bool propto__, typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>*>
stan::promote_args_t<T0__>
Jeffreys_sigma_lpdf(const T0__& sigma, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__>;
  int current_statement__ = 0;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 69;
    return stan::math::log((1 / sigma));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T1__>>
coefs_lb(const std::vector<int>& type_in, const T1__& bound_in_arg__,
         std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& bound_in = stan::math::to_ref(bound_in_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int type = std::numeric_limits<int>::min();
    local_scalar_t__ bound = DUMMY_VAR__;
    local_scalar_t__ lb = DUMMY_VAR__;
    current_statement__ = 79;
    if (stan::math::logical_eq(stan::math::num_elements(type_in), 0)) {
      current_statement__ = 77;
      return stan::math::negative_infinity();
    } else {
      current_statement__ = 74;
      type = stan::model::rvalue(type_in, "type_in",
               stan::model::index_uni(1));
      current_statement__ = 75;
      bound = stan::model::rvalue(bound_in, "bound_in",
                stan::model::index_uni(1));
    }
    current_statement__ = 82;
    if (stan::math::logical_eq(type, 0)) {
      current_statement__ = 81;
      lb = stan::math::negative_infinity();
    } else {
      current_statement__ = 80;
      lb = bound;
    }
    current_statement__ = 83;
    return lb;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T1__>>
coefs_ub(const std::vector<int>& type_in, const T1__& bound_in_arg__,
         std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& bound_in = stan::math::to_ref(bound_in_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int type = std::numeric_limits<int>::min();
    local_scalar_t__ bound = DUMMY_VAR__;
    local_scalar_t__ lb = DUMMY_VAR__;
    current_statement__ = 93;
    if (stan::math::logical_eq(stan::math::num_elements(type_in), 0)) {
      current_statement__ = 91;
      return stan::math::positive_infinity();
    } else {
      current_statement__ = 88;
      type = stan::model::rvalue(type_in, "type_in",
               stan::model::index_uni(2));
      current_statement__ = 89;
      bound = stan::model::rvalue(bound_in, "bound_in",
                stan::model::index_uni(2));
    }
    current_statement__ = 96;
    if (stan::math::logical_eq(type, 0)) {
      current_statement__ = 95;
      lb = stan::math::positive_infinity();
    } else {
      current_statement__ = 94;
      lb = bound;
    }
    current_statement__ = 97;
    return lb;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T1__>>
data_lb(const int& is_trunc, const T1__& trunc_in_arg__, std::ostream*
        pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& trunc_in = stan::math::to_ref(trunc_in_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ lb = DUMMY_VAR__;
    current_statement__ = 102;
    if (stan::math::logical_eq(is_trunc, 0)) {
      current_statement__ = 101;
      lb = stan::math::negative_infinity();
    } else {
      current_statement__ = 100;
      lb = stan::model::rvalue(trunc_in, "trunc_in",
             stan::model::index_uni(1));
    }
    current_statement__ = 103;
    return lb;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T1__>>
data_ub(const int& is_trunc, const T1__& trunc_in_arg__, std::ostream*
        pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& trunc_in = stan::math::to_ref(trunc_in_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ ub = DUMMY_VAR__;
    current_statement__ = 108;
    if (stan::math::logical_eq(is_trunc, 0)) {
      current_statement__ = 107;
      ub = stan::math::positive_infinity();
    } else {
      current_statement__ = 106;
      ub = stan::model::rvalue(trunc_in, "trunc_in",
             stan::model::index_uni(2));
    }
    current_statement__ = 109;
    return ub;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T2__, typename T4__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>>*>
stan::promote_args_t<T0__, stan::base_type_t<T2__>, stan::base_type_t<T4__>>
set_prior(const T0__& parameter, const int& prior_type, const T2__&
          prior_parameters_arg__, const std::vector<int>& bounds_type,
          const T4__& bounds_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T4__>>;
  int current_statement__ = 0;
  const auto& prior_parameters = stan::math::to_ref(prior_parameters_arg__);
  const auto& bounds = stan::math::to_ref(bounds_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ ll = DUMMY_VAR__;
    current_statement__ = 216;
    if (stan::math::logical_eq(prior_type, 1)) {
      current_statement__ = 205;
      ll = stan::math::normal_lpdf<false>(parameter,
             stan::model::rvalue(prior_parameters, "prior_parameters",
               stan::model::index_uni(1)),
             stan::model::rvalue(prior_parameters, "prior_parameters",
               stan::model::index_uni(2)));
      current_statement__ = 214;
      if ((stan::math::primitive_value(
             stan::math::logical_neq(
               stan::model::rvalue(bounds_type, "bounds_type",
                 stan::model::index_uni(1)), 0))
          &&
          stan::math::primitive_value(
            stan::math::logical_neq(
              stan::model::rvalue(bounds_type, "bounds_type",
                stan::model::index_uni(2)), 0)))) {
        current_statement__ = 212;
        ll = (ll -
          stan::math::log_diff_exp(
            stan::math::normal_lcdf(
              stan::model::rvalue(bounds, "bounds", stan::model::index_uni(2)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(2))),
            stan::math::normal_lcdf(
              stan::model::rvalue(bounds, "bounds", stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(2)))));
      } else {
        current_statement__ = 211;
        if (stan::math::logical_neq(
              stan::model::rvalue(bounds_type, "bounds_type",
                stan::model::index_uni(1)), 0)) {
          current_statement__ = 209;
          ll = (ll -
            stan::math::normal_lccdf(
              stan::model::rvalue(bounds, "bounds", stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(2))));
        } else {
          current_statement__ = 208;
          if (stan::math::logical_neq(
                stan::model::rvalue(bounds_type, "bounds_type",
                  stan::model::index_uni(2)), 0)) {
            current_statement__ = 206;
            ll = (ll -
              stan::math::normal_lcdf(
                stan::model::rvalue(bounds, "bounds",
                  stan::model::index_uni(2)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(2))));
          }
        }
      }
    } else {
      current_statement__ = 204;
      if (stan::math::logical_eq(prior_type, 2)) {
        current_statement__ = 193;
        ll = stan::math::lognormal_lpdf<false>(parameter,
               stan::model::rvalue(prior_parameters, "prior_parameters",
                 stan::model::index_uni(1)),
               stan::model::rvalue(prior_parameters, "prior_parameters",
                 stan::model::index_uni(2)));
        current_statement__ = 202;
        if ((stan::math::primitive_value(
               stan::math::logical_neq(
                 stan::model::rvalue(bounds_type, "bounds_type",
                   stan::model::index_uni(1)), 0))
            &&
            stan::math::primitive_value(
              stan::math::logical_neq(
                stan::model::rvalue(bounds_type, "bounds_type",
                  stan::model::index_uni(2)), 0)))) {
          current_statement__ = 200;
          ll = (ll -
            stan::math::log_diff_exp(
              stan::math::lognormal_lcdf(
                stan::model::rvalue(bounds, "bounds",
                  stan::model::index_uni(2)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(2))),
              stan::math::lognormal_lcdf(
                stan::model::rvalue(bounds, "bounds",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(2)))));
        } else {
          current_statement__ = 199;
          if (stan::math::logical_neq(
                stan::model::rvalue(bounds_type, "bounds_type",
                  stan::model::index_uni(1)), 0)) {
            current_statement__ = 197;
            ll = (ll -
              stan::math::lognormal_lccdf(
                stan::model::rvalue(bounds, "bounds",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(2))));
          } else {
            current_statement__ = 196;
            if (stan::math::logical_neq(
                  stan::model::rvalue(bounds_type, "bounds_type",
                    stan::model::index_uni(2)), 0)) {
              current_statement__ = 194;
              ll = (ll -
                stan::math::lognormal_lcdf(
                  stan::model::rvalue(bounds, "bounds",
                    stan::model::index_uni(2)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(2))));
            }
          }
        }
      } else {
        current_statement__ = 192;
        if (stan::math::logical_eq(prior_type, 3)) {
          current_statement__ = 181;
          ll = stan::math::cauchy_lpdf<false>(parameter,
                 stan::model::rvalue(prior_parameters, "prior_parameters",
                   stan::model::index_uni(1)),
                 stan::model::rvalue(prior_parameters, "prior_parameters",
                   stan::model::index_uni(2)));
          current_statement__ = 190;
          if ((stan::math::primitive_value(
                 stan::math::logical_neq(
                   stan::model::rvalue(bounds_type, "bounds_type",
                     stan::model::index_uni(1)), 0))
              &&
              stan::math::primitive_value(
                stan::math::logical_neq(
                  stan::model::rvalue(bounds_type, "bounds_type",
                    stan::model::index_uni(2)), 0)))) {
            current_statement__ = 188;
            ll = (ll -
              stan::math::log_diff_exp(
                stan::math::cauchy_lcdf(
                  stan::model::rvalue(bounds, "bounds",
                    stan::model::index_uni(2)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(2))),
                stan::math::cauchy_lcdf(
                  stan::model::rvalue(bounds, "bounds",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(2)))));
          } else {
            current_statement__ = 187;
            if (stan::math::logical_neq(
                  stan::model::rvalue(bounds_type, "bounds_type",
                    stan::model::index_uni(1)), 0)) {
              current_statement__ = 185;
              ll = (ll -
                stan::math::cauchy_lccdf(
                  stan::model::rvalue(bounds, "bounds",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(2))));
            } else {
              current_statement__ = 184;
              if (stan::math::logical_neq(
                    stan::model::rvalue(bounds_type, "bounds_type",
                      stan::model::index_uni(2)), 0)) {
                current_statement__ = 182;
                ll = (ll -
                  stan::math::cauchy_lcdf(
                    stan::model::rvalue(bounds, "bounds",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(2))));
              }
            }
          }
        } else {
          current_statement__ = 180;
          if (stan::math::logical_eq(prior_type, 4)) {
            current_statement__ = 169;
            ll = stan::math::student_t_lpdf<false>(parameter,
                   stan::model::rvalue(prior_parameters, "prior_parameters",
                     stan::model::index_uni(1)),
                   stan::model::rvalue(prior_parameters, "prior_parameters",
                     stan::model::index_uni(2)),
                   stan::model::rvalue(prior_parameters, "prior_parameters",
                     stan::model::index_uni(3)));
            current_statement__ = 178;
            if ((stan::math::primitive_value(
                   stan::math::logical_neq(
                     stan::model::rvalue(bounds_type, "bounds_type",
                       stan::model::index_uni(1)), 0))
                &&
                stan::math::primitive_value(
                  stan::math::logical_neq(
                    stan::model::rvalue(bounds_type, "bounds_type",
                      stan::model::index_uni(2)), 0)))) {
              current_statement__ = 176;
              ll = (ll -
                stan::math::log_diff_exp(
                  stan::math::student_t_lcdf(
                    stan::model::rvalue(bounds, "bounds",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(3))),
                  stan::math::student_t_lcdf(
                    stan::model::rvalue(bounds, "bounds",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(3)))));
            } else {
              current_statement__ = 175;
              if (stan::math::logical_neq(
                    stan::model::rvalue(bounds_type, "bounds_type",
                      stan::model::index_uni(1)), 0)) {
                current_statement__ = 173;
                ll = (ll -
                  stan::math::student_t_lccdf(
                    stan::model::rvalue(bounds, "bounds",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(3))));
              } else {
                current_statement__ = 172;
                if (stan::math::logical_neq(
                      stan::model::rvalue(bounds_type, "bounds_type",
                        stan::model::index_uni(2)), 0)) {
                  current_statement__ = 170;
                  ll = (ll -
                    stan::math::student_t_lcdf(
                      stan::model::rvalue(bounds, "bounds",
                        stan::model::index_uni(2)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(2)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(3))));
                }
              }
            }
          } else {
            current_statement__ = 168;
            if (stan::math::logical_eq(prior_type, 5)) {
              current_statement__ = 157;
              ll = stan::math::gamma_lpdf<false>(parameter,
                     stan::model::rvalue(prior_parameters,
                       "prior_parameters", stan::model::index_uni(1)),
                     stan::model::rvalue(prior_parameters,
                       "prior_parameters", stan::model::index_uni(2)));
              current_statement__ = 166;
              if ((stan::math::primitive_value(
                     stan::math::logical_neq(
                       stan::model::rvalue(bounds_type, "bounds_type",
                         stan::model::index_uni(1)), 0))
                  &&
                  stan::math::primitive_value(
                    stan::math::logical_neq(
                      stan::model::rvalue(bounds_type, "bounds_type",
                        stan::model::index_uni(2)), 0)))) {
                current_statement__ = 164;
                ll = (ll -
                  stan::math::log_diff_exp(
                    stan::math::gamma_lcdf(
                      stan::model::rvalue(bounds, "bounds",
                        stan::model::index_uni(2)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(2))),
                    stan::math::gamma_lcdf(
                      stan::model::rvalue(bounds, "bounds",
                        stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(2)))));
              } else {
                current_statement__ = 163;
                if (stan::math::logical_neq(
                      stan::model::rvalue(bounds_type, "bounds_type",
                        stan::model::index_uni(1)), 0)) {
                  current_statement__ = 161;
                  ll = (ll -
                    stan::math::gamma_lccdf(
                      stan::model::rvalue(bounds, "bounds",
                        stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(2))));
                } else {
                  current_statement__ = 160;
                  if (stan::math::logical_neq(
                        stan::model::rvalue(bounds_type, "bounds_type",
                          stan::model::index_uni(2)), 0)) {
                    current_statement__ = 158;
                    ll = (ll -
                      stan::math::gamma_lcdf(
                        stan::model::rvalue(bounds, "bounds",
                          stan::model::index_uni(2)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(2))));
                  }
                }
              }
            } else {
              current_statement__ = 156;
              if (stan::math::logical_eq(prior_type, 6)) {
                current_statement__ = 145;
                ll = stan::math::inv_gamma_lpdf<false>(parameter,
                       stan::model::rvalue(prior_parameters,
                         "prior_parameters", stan::model::index_uni(1)),
                       stan::model::rvalue(prior_parameters,
                         "prior_parameters", stan::model::index_uni(2)));
                current_statement__ = 154;
                if ((stan::math::primitive_value(
                       stan::math::logical_neq(
                         stan::model::rvalue(bounds_type, "bounds_type",
                           stan::model::index_uni(1)), 0))
                    &&
                    stan::math::primitive_value(
                      stan::math::logical_neq(
                        stan::model::rvalue(bounds_type, "bounds_type",
                          stan::model::index_uni(2)), 0)))) {
                  current_statement__ = 152;
                  ll = (ll -
                    stan::math::log_diff_exp(
                      stan::math::inv_gamma_lcdf(
                        stan::model::rvalue(bounds, "bounds",
                          stan::model::index_uni(2)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(2))),
                      stan::math::inv_gamma_lcdf(
                        stan::model::rvalue(bounds, "bounds",
                          stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(2)))));
                } else {
                  current_statement__ = 151;
                  if (stan::math::logical_neq(
                        stan::model::rvalue(bounds_type, "bounds_type",
                          stan::model::index_uni(1)), 0)) {
                    current_statement__ = 149;
                    ll = (ll -
                      stan::math::inv_gamma_lccdf(
                        stan::model::rvalue(bounds, "bounds",
                          stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(2))));
                  } else {
                    current_statement__ = 148;
                    if (stan::math::logical_neq(
                          stan::model::rvalue(bounds_type, "bounds_type",
                            stan::model::index_uni(2)), 0)) {
                      current_statement__ = 146;
                      ll = (ll -
                        stan::math::inv_gamma_lcdf(
                          stan::model::rvalue(bounds, "bounds",
                            stan::model::index_uni(2)),
                          stan::model::rvalue(prior_parameters,
                            "prior_parameters", stan::model::index_uni(1)),
                          stan::model::rvalue(prior_parameters,
                            "prior_parameters", stan::model::index_uni(2))));
                    }
                  }
                }
              } else {
                current_statement__ = 144;
                if (stan::math::logical_eq(prior_type, 7)) {
                  current_statement__ = 142;
                  ll = stan::math::uniform_lpdf<false>(parameter,
                         stan::model::rvalue(prior_parameters,
                           "prior_parameters", stan::model::index_uni(1)),
                         stan::model::rvalue(prior_parameters,
                           "prior_parameters", stan::model::index_uni(2)));
                } else {
                  current_statement__ = 141;
                  if (stan::math::logical_eq(prior_type, 8)) {
                    current_statement__ = 130;
                    ll = stan::math::beta_lpdf<false>(parameter,
                           stan::model::rvalue(prior_parameters,
                             "prior_parameters", stan::model::index_uni(1)),
                           stan::model::rvalue(prior_parameters,
                             "prior_parameters", stan::model::index_uni(2)));
                    current_statement__ = 139;
                    if ((stan::math::primitive_value(
                           stan::math::logical_neq(
                             stan::model::rvalue(bounds_type, "bounds_type",
                               stan::model::index_uni(1)), 0))
                        &&
                        stan::math::primitive_value(
                          stan::math::logical_neq(
                            stan::model::rvalue(bounds_type, "bounds_type",
                              stan::model::index_uni(2)), 0)))) {
                      current_statement__ = 137;
                      ll = (ll -
                        stan::math::log_diff_exp(
                          stan::math::beta_lcdf(
                            stan::model::rvalue(bounds, "bounds",
                              stan::model::index_uni(2)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(2))),
                          stan::math::beta_lcdf(
                            stan::model::rvalue(bounds, "bounds",
                              stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(2)))));
                    } else {
                      current_statement__ = 136;
                      if (stan::math::logical_neq(
                            stan::model::rvalue(bounds_type, "bounds_type",
                              stan::model::index_uni(1)), 0)) {
                        current_statement__ = 134;
                        ll = (ll -
                          stan::math::beta_lccdf(
                            stan::model::rvalue(bounds, "bounds",
                              stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(2))));
                      } else {
                        current_statement__ = 133;
                        if (stan::math::logical_neq(
                              stan::model::rvalue(bounds_type, "bounds_type",
                                stan::model::index_uni(2)), 0)) {
                          current_statement__ = 131;
                          ll = (ll -
                            stan::math::beta_lcdf(
                              stan::model::rvalue(bounds, "bounds",
                                stan::model::index_uni(2)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(1)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(2))));
                        }
                      }
                    }
                  } else {
                    current_statement__ = 129;
                    if (stan::math::logical_eq(prior_type, 9)) {
                      current_statement__ = 118;
                      ll = stan::math::exponential_lpdf<false>(parameter,
                             stan::model::rvalue(prior_parameters,
                               "prior_parameters", stan::model::index_uni(1)));
                      current_statement__ = 127;
                      if ((stan::math::primitive_value(
                             stan::math::logical_neq(
                               stan::model::rvalue(bounds_type,
                                 "bounds_type", stan::model::index_uni(1)), 0))
                          &&
                          stan::math::primitive_value(
                            stan::math::logical_neq(
                              stan::model::rvalue(bounds_type, "bounds_type",
                                stan::model::index_uni(2)), 0)))) {
                        current_statement__ = 125;
                        ll = (ll -
                          stan::math::log_diff_exp(
                            stan::math::exponential_lcdf(
                              stan::model::rvalue(bounds, "bounds",
                                stan::model::index_uni(2)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(1))),
                            stan::math::exponential_lcdf(
                              stan::model::rvalue(bounds, "bounds",
                                stan::model::index_uni(1)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(1)))));
                      } else {
                        current_statement__ = 124;
                        if (stan::math::logical_neq(
                              stan::model::rvalue(bounds_type, "bounds_type",
                                stan::model::index_uni(1)), 0)) {
                          current_statement__ = 122;
                          ll = (ll -
                            stan::math::exponential_lccdf(
                              stan::model::rvalue(bounds, "bounds",
                                stan::model::index_uni(1)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(1))));
                        } else {
                          current_statement__ = 121;
                          if (stan::math::logical_neq(
                                stan::model::rvalue(bounds_type,
                                  "bounds_type", stan::model::index_uni(2)),
                                0)) {
                            current_statement__ = 119;
                            ll = (ll -
                              stan::math::exponential_lcdf(
                                stan::model::rvalue(bounds, "bounds",
                                  stan::model::index_uni(2)),
                                stan::model::rvalue(prior_parameters,
                                  "prior_parameters",
                                  stan::model::index_uni(1))));
                          }
                        }
                      }
                    } else {
                      current_statement__ = 117;
                      if (stan::math::logical_eq(prior_type, 98)) {
                        current_statement__ = 115;
                        ll = Jeffreys_mu_lpdf<false>(parameter, pstream__);
                      } else {
                        current_statement__ = 114;
                        if (stan::math::logical_eq(prior_type, 99)) {
                          current_statement__ = 112;
                          ll = Jeffreys_sigma_lpdf<false>(parameter,
                                 pstream__);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    current_statement__ = 217;
    return ll;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_t final : public model_base_crtp<model_t> {
private:
  int N;
  Eigen::Matrix<double,-1,1> x_data__;
  int estimate_mu;
  int estimate_sigma;
  int estimate_nu;
  Eigen::Matrix<double,-1,1> bounds_mu_data__;
  Eigen::Matrix<double,-1,1> bounds_sigma_data__;
  Eigen::Matrix<double,-1,1> bounds_nu_data__;
  std::vector<int> bounds_type_mu;
  std::vector<int> bounds_type_sigma;
  std::vector<int> bounds_type_nu;
  std::vector<double> fixed_mu;
  std::vector<double> fixed_sigma;
  std::vector<double> fixed_nu;
  Eigen::Matrix<double,-1,1> prior_parameters_mu_data__;
  Eigen::Matrix<double,-1,1> prior_parameters_sigma_data__;
  Eigen::Matrix<double,-1,1> prior_parameters_nu_data__;
  int prior_type_mu;
  int prior_type_sigma;
  int prior_type_nu;
  int sample_priors;
  Eigen::Map<Eigen::Matrix<double,-1,1>> x{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> bounds_mu{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> bounds_sigma{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> bounds_nu{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_parameters_mu{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_parameters_sigma{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_parameters_nu{nullptr, 0};
public:
  ~model_t() {}
  model_t(stan::io::var_context& context__, unsigned int random_seed__ = 0,
          std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ = "model_t_namespace::model_t";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 30;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 30;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("x", "N", N);
      current_statement__ = 32;
      context__.validate_dims("data initialization", "x", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      x_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&x) Eigen::Map<Eigen::Matrix<double,-1,1>>(x_data__.data(), N);
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 32;
        x_flat__ = context__.vals_r("x");
        current_statement__ = 32;
        pos__ = 1;
        current_statement__ = 32;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 32;
          stan::model::assign(x, x_flat__[(pos__ - 1)],
            "assigning variable x", stan::model::index_uni(sym1__));
          current_statement__ = 32;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 33;
      context__.validate_dims("data initialization", "estimate_mu", "int",
        std::vector<size_t>{});
      estimate_mu = std::numeric_limits<int>::min();
      current_statement__ = 33;
      estimate_mu = context__.vals_i("estimate_mu")[(1 - 1)];
      current_statement__ = 34;
      context__.validate_dims("data initialization", "estimate_sigma", "int",
        std::vector<size_t>{});
      estimate_sigma = std::numeric_limits<int>::min();
      current_statement__ = 34;
      estimate_sigma = context__.vals_i("estimate_sigma")[(1 - 1)];
      current_statement__ = 35;
      context__.validate_dims("data initialization", "estimate_nu", "int",
        std::vector<size_t>{});
      estimate_nu = std::numeric_limits<int>::min();
      current_statement__ = 35;
      estimate_nu = context__.vals_i("estimate_nu")[(1 - 1)];
      current_statement__ = 36;
      stan::math::validate_non_negative_index("bounds_mu",
        "estimate_mu == 1 ? 2 : 0",
        (stan::math::logical_eq(estimate_mu, 1) ? 2 : 0));
      current_statement__ = 37;
      context__.validate_dims("data initialization", "bounds_mu", "double",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_mu, 1) ? 2 : 0))});
      bounds_mu_data__ = Eigen::Matrix<double,-1,1>::Constant((stan::math::logical_eq(
                                                                 estimate_mu,
                                                                 1) ? 2 : 0),
                           std::numeric_limits<double>::quiet_NaN());
      new (&bounds_mu)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(bounds_mu_data__.data(),
        (stan::math::logical_eq(estimate_mu, 1) ? 2 : 0));
      {
        std::vector<local_scalar_t__> bounds_mu_flat__;
        current_statement__ = 37;
        bounds_mu_flat__ = context__.vals_r("bounds_mu");
        current_statement__ = 37;
        pos__ = 1;
        current_statement__ = 37;
        for (int sym1__ = 1; sym1__ <=
             (stan::math::logical_eq(estimate_mu, 1) ? 2 : 0); ++sym1__) {
          current_statement__ = 37;
          stan::model::assign(bounds_mu, bounds_mu_flat__[(pos__ - 1)],
            "assigning variable bounds_mu", stan::model::index_uni(sym1__));
          current_statement__ = 37;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 38;
      stan::math::validate_non_negative_index("bounds_sigma",
        "estimate_sigma == 1 ? 2 : 0",
        (stan::math::logical_eq(estimate_sigma, 1) ? 2 : 0));
      current_statement__ = 39;
      context__.validate_dims("data initialization", "bounds_sigma",
        "double",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_sigma, 1) ? 2 : 0))});
      bounds_sigma_data__ = Eigen::Matrix<double,-1,1>::Constant((stan::math::logical_eq(
                                                                    estimate_sigma,
                                                                    1) ? 2 : 0),
                              std::numeric_limits<double>::quiet_NaN());
      new (&bounds_sigma)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(bounds_sigma_data__.data(),
        (stan::math::logical_eq(estimate_sigma, 1) ? 2 : 0));
      {
        std::vector<local_scalar_t__> bounds_sigma_flat__;
        current_statement__ = 39;
        bounds_sigma_flat__ = context__.vals_r("bounds_sigma");
        current_statement__ = 39;
        pos__ = 1;
        current_statement__ = 39;
        for (int sym1__ = 1; sym1__ <=
             (stan::math::logical_eq(estimate_sigma, 1) ? 2 : 0); ++sym1__) {
          current_statement__ = 39;
          stan::model::assign(bounds_sigma, bounds_sigma_flat__[(pos__ - 1)],
            "assigning variable bounds_sigma", stan::model::index_uni(sym1__));
          current_statement__ = 39;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 40;
      stan::math::validate_non_negative_index("bounds_nu",
        "estimate_nu == 1 ? 2 : 0",
        (stan::math::logical_eq(estimate_nu, 1) ? 2 : 0));
      current_statement__ = 41;
      context__.validate_dims("data initialization", "bounds_nu", "double",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_nu, 1) ? 2 : 0))});
      bounds_nu_data__ = Eigen::Matrix<double,-1,1>::Constant((stan::math::logical_eq(
                                                                 estimate_nu,
                                                                 1) ? 2 : 0),
                           std::numeric_limits<double>::quiet_NaN());
      new (&bounds_nu)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(bounds_nu_data__.data(),
        (stan::math::logical_eq(estimate_nu, 1) ? 2 : 0));
      {
        std::vector<local_scalar_t__> bounds_nu_flat__;
        current_statement__ = 41;
        bounds_nu_flat__ = context__.vals_r("bounds_nu");
        current_statement__ = 41;
        pos__ = 1;
        current_statement__ = 41;
        for (int sym1__ = 1; sym1__ <=
             (stan::math::logical_eq(estimate_nu, 1) ? 2 : 0); ++sym1__) {
          current_statement__ = 41;
          stan::model::assign(bounds_nu, bounds_nu_flat__[(pos__ - 1)],
            "assigning variable bounds_nu", stan::model::index_uni(sym1__));
          current_statement__ = 41;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 42;
      stan::math::validate_non_negative_index("bounds_type_mu",
        "estimate_mu == 1 ? 2 : 0",
        (stan::math::logical_eq(estimate_mu, 1) ? 2 : 0));
      current_statement__ = 43;
      context__.validate_dims("data initialization", "bounds_type_mu", "int",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_mu, 1) ? 2 : 0))});
      bounds_type_mu = std::vector<int>((stan::math::logical_eq(estimate_mu,
                                           1) ? 2 : 0),
                         std::numeric_limits<int>::min());
      current_statement__ = 43;
      bounds_type_mu = context__.vals_i("bounds_type_mu");
      current_statement__ = 44;
      stan::math::validate_non_negative_index("bounds_type_sigma",
        "estimate_sigma == 1 ? 2 : 0",
        (stan::math::logical_eq(estimate_sigma, 1) ? 2 : 0));
      current_statement__ = 45;
      context__.validate_dims("data initialization", "bounds_type_sigma",
        "int",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_sigma, 1) ? 2 : 0))});
      bounds_type_sigma = std::vector<int>((stan::math::logical_eq(
                                              estimate_sigma, 1) ? 2 : 0),
                            std::numeric_limits<int>::min());
      current_statement__ = 45;
      bounds_type_sigma = context__.vals_i("bounds_type_sigma");
      current_statement__ = 46;
      stan::math::validate_non_negative_index("bounds_type_nu",
        "estimate_nu == 1 ? 2 : 0",
        (stan::math::logical_eq(estimate_nu, 1) ? 2 : 0));
      current_statement__ = 47;
      context__.validate_dims("data initialization", "bounds_type_nu", "int",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_nu, 1) ? 2 : 0))});
      bounds_type_nu = std::vector<int>((stan::math::logical_eq(estimate_nu,
                                           1) ? 2 : 0),
                         std::numeric_limits<int>::min());
      current_statement__ = 47;
      bounds_type_nu = context__.vals_i("bounds_type_nu");
      current_statement__ = 48;
      stan::math::validate_non_negative_index("fixed_mu",
        "estimate_mu == 0 ? 1 : 0",
        (stan::math::logical_eq(estimate_mu, 0) ? 1 : 0));
      current_statement__ = 49;
      context__.validate_dims("data initialization", "fixed_mu", "double",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_mu, 0) ? 1 : 0))});
      fixed_mu = std::vector<double>((stan::math::logical_eq(estimate_mu, 0) ? 1 : 0),
                   std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 49;
      fixed_mu = context__.vals_r("fixed_mu");
      current_statement__ = 50;
      stan::math::validate_non_negative_index("fixed_sigma",
        "estimate_sigma == 0 ? 1 : 0",
        (stan::math::logical_eq(estimate_sigma, 0) ? 1 : 0));
      current_statement__ = 51;
      context__.validate_dims("data initialization", "fixed_sigma", "double",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_sigma, 0) ? 1 : 0))});
      fixed_sigma = std::vector<double>((stan::math::logical_eq(
                                           estimate_sigma, 0) ? 1 : 0),
                      std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 51;
      fixed_sigma = context__.vals_r("fixed_sigma");
      current_statement__ = 52;
      stan::math::validate_non_negative_index("fixed_nu",
        "estimate_nu == 0 ? 1 : 0",
        (stan::math::logical_eq(estimate_nu, 0) ? 1 : 0));
      current_statement__ = 53;
      context__.validate_dims("data initialization", "fixed_nu", "double",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_nu, 0) ? 1 : 0))});
      fixed_nu = std::vector<double>((stan::math::logical_eq(estimate_nu, 0) ? 1 : 0),
                   std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 53;
      fixed_nu = context__.vals_r("fixed_nu");
      current_statement__ = 54;
      stan::math::validate_non_negative_index("prior_parameters_mu",
        "estimate_mu == 1 ? 3 : 0",
        (stan::math::logical_eq(estimate_mu, 1) ? 3 : 0));
      current_statement__ = 55;
      context__.validate_dims("data initialization", "prior_parameters_mu",
        "double",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_mu, 1) ? 3 : 0))});
      prior_parameters_mu_data__ = Eigen::Matrix<double,-1,1>::Constant((
                                     stan::math::logical_eq(estimate_mu, 1) ? 3 : 0),
                                     std::numeric_limits<double>::quiet_NaN());
      new (&prior_parameters_mu)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_parameters_mu_data__.data(),
        (stan::math::logical_eq(estimate_mu, 1) ? 3 : 0));
      {
        std::vector<local_scalar_t__> prior_parameters_mu_flat__;
        current_statement__ = 55;
        prior_parameters_mu_flat__ = context__.vals_r("prior_parameters_mu");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <=
             (stan::math::logical_eq(estimate_mu, 1) ? 3 : 0); ++sym1__) {
          current_statement__ = 55;
          stan::model::assign(prior_parameters_mu,
            prior_parameters_mu_flat__[(pos__ - 1)],
            "assigning variable prior_parameters_mu",
            stan::model::index_uni(sym1__));
          current_statement__ = 55;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 56;
      stan::math::validate_non_negative_index("prior_parameters_sigma",
        "estimate_sigma == 1 ? 3 : 0",
        (stan::math::logical_eq(estimate_sigma, 1) ? 3 : 0));
      current_statement__ = 57;
      context__.validate_dims("data initialization",
        "prior_parameters_sigma", "double",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_sigma, 1) ? 3 : 0))});
      prior_parameters_sigma_data__ = Eigen::Matrix<double,-1,1>::Constant((
                                        stan::math::logical_eq(
                                          estimate_sigma, 1) ? 3 : 0),
                                        std::numeric_limits<double>::quiet_NaN(
                                          ));
      new (&prior_parameters_sigma)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_parameters_sigma_data__.data(),
        (stan::math::logical_eq(estimate_sigma, 1) ? 3 : 0));
      {
        std::vector<local_scalar_t__> prior_parameters_sigma_flat__;
        current_statement__ = 57;
        prior_parameters_sigma_flat__ = context__.vals_r("prior_parameters_sigma");
        current_statement__ = 57;
        pos__ = 1;
        current_statement__ = 57;
        for (int sym1__ = 1; sym1__ <=
             (stan::math::logical_eq(estimate_sigma, 1) ? 3 : 0); ++sym1__) {
          current_statement__ = 57;
          stan::model::assign(prior_parameters_sigma,
            prior_parameters_sigma_flat__[(pos__ - 1)],
            "assigning variable prior_parameters_sigma",
            stan::model::index_uni(sym1__));
          current_statement__ = 57;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 58;
      stan::math::validate_non_negative_index("prior_parameters_nu",
        "estimate_nu == 1 ? 3 : 0",
        (stan::math::logical_eq(estimate_nu, 1) ? 3 : 0));
      current_statement__ = 59;
      context__.validate_dims("data initialization", "prior_parameters_nu",
        "double",
        std::vector<size_t>{static_cast<size_t>(
                              (stan::math::logical_eq(estimate_nu, 1) ? 3 : 0))});
      prior_parameters_nu_data__ = Eigen::Matrix<double,-1,1>::Constant((
                                     stan::math::logical_eq(estimate_nu, 1) ? 3 : 0),
                                     std::numeric_limits<double>::quiet_NaN());
      new (&prior_parameters_nu)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_parameters_nu_data__.data(),
        (stan::math::logical_eq(estimate_nu, 1) ? 3 : 0));
      {
        std::vector<local_scalar_t__> prior_parameters_nu_flat__;
        current_statement__ = 59;
        prior_parameters_nu_flat__ = context__.vals_r("prior_parameters_nu");
        current_statement__ = 59;
        pos__ = 1;
        current_statement__ = 59;
        for (int sym1__ = 1; sym1__ <=
             (stan::math::logical_eq(estimate_nu, 1) ? 3 : 0); ++sym1__) {
          current_statement__ = 59;
          stan::model::assign(prior_parameters_nu,
            prior_parameters_nu_flat__[(pos__ - 1)],
            "assigning variable prior_parameters_nu",
            stan::model::index_uni(sym1__));
          current_statement__ = 59;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 60;
      context__.validate_dims("data initialization", "prior_type_mu", "int",
        std::vector<size_t>{});
      prior_type_mu = std::numeric_limits<int>::min();
      current_statement__ = 60;
      prior_type_mu = context__.vals_i("prior_type_mu")[(1 - 1)];
      current_statement__ = 61;
      context__.validate_dims("data initialization", "prior_type_sigma",
        "int", std::vector<size_t>{});
      prior_type_sigma = std::numeric_limits<int>::min();
      current_statement__ = 61;
      prior_type_sigma = context__.vals_i("prior_type_sigma")[(1 - 1)];
      current_statement__ = 62;
      context__.validate_dims("data initialization", "prior_type_nu", "int",
        std::vector<size_t>{});
      prior_type_nu = std::numeric_limits<int>::min();
      current_statement__ = 62;
      prior_type_nu = context__.vals_i("prior_type_nu")[(1 - 1)];
      current_statement__ = 63;
      context__.validate_dims("data initialization", "sample_priors", "int",
        std::vector<size_t>{});
      sample_priors = std::numeric_limits<int>::min();
      current_statement__ = 63;
      sample_priors = context__.vals_i("sample_priors")[(1 - 1)];
      current_statement__ = 64;
      stan::math::validate_non_negative_index("mu_est", "estimate_mu",
        estimate_mu);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("sigma_est", "estimate_sigma",
        estimate_sigma);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("nu_est", "estimate_nu",
        estimate_nu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = estimate_mu + estimate_sigma + estimate_nu;
  }
  inline std::string model_name() const final {
    return "model_t";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ = "model_t_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<local_scalar_t__> mu_est =
        std::vector<local_scalar_t__>(estimate_mu, DUMMY_VAR__);
      current_statement__ = 1;
      mu_est = in__.template read_constrain_lub<
                 std::vector<local_scalar_t__>,
                 jacobian__>(coefs_lb(bounds_type_mu, bounds_mu, pstream__),
                 coefs_ub(bounds_type_mu, bounds_mu, pstream__), lp__,
                 estimate_mu);
      std::vector<local_scalar_t__> sigma_est =
        std::vector<local_scalar_t__>(estimate_sigma, DUMMY_VAR__);
      current_statement__ = 2;
      sigma_est = in__.template read_constrain_lub<
                    std::vector<local_scalar_t__>,
                    jacobian__>(coefs_lb(bounds_type_sigma, bounds_sigma,
                                  pstream__),
                    coefs_ub(bounds_type_sigma, bounds_sigma, pstream__),
                    lp__, estimate_sigma);
      std::vector<local_scalar_t__> nu_est =
        std::vector<local_scalar_t__>(estimate_nu, DUMMY_VAR__);
      current_statement__ = 3;
      nu_est = in__.template read_constrain_lub<
                 std::vector<local_scalar_t__>,
                 jacobian__>(coefs_lb(bounds_type_nu, bounds_nu, pstream__),
                 coefs_ub(bounds_type_nu, bounds_nu, pstream__), lp__,
                 estimate_nu);
      local_scalar_t__ mu = DUMMY_VAR__;
      local_scalar_t__ scale = DUMMY_VAR__;
      local_scalar_t__ nu = DUMMY_VAR__;
      current_statement__ = 11;
      if (stan::math::logical_eq(estimate_nu, 1)) {
        current_statement__ = 9;
        nu = (stan::model::rvalue(nu_est, "nu_est", stan::model::index_uni(1))
          + 2);
      } else {
        current_statement__ = 7;
        nu = stan::model::rvalue(fixed_nu, "fixed_nu",
               stan::model::index_uni(1));
      }
      current_statement__ = 16;
      if (stan::math::logical_eq(estimate_mu, 1)) {
        current_statement__ = 14;
        mu = stan::model::rvalue(mu_est, "mu_est", stan::model::index_uni(1));
      } else {
        current_statement__ = 12;
        mu = stan::model::rvalue(fixed_mu, "fixed_mu",
               stan::model::index_uni(1));
      }
      current_statement__ = 21;
      if (stan::math::logical_eq(estimate_sigma, 1)) {
        current_statement__ = 19;
        scale = (stan::model::rvalue(sigma_est, "sigma_est",
                   stan::model::index_uni(1))
          / stan::math::sqrt((nu / (nu - 2.0))));
      } else {
        current_statement__ = 17;
        scale = (stan::model::rvalue(fixed_sigma, "fixed_sigma",
                   stan::model::index_uni(1))
          / stan::math::sqrt((nu / (nu - 2.0))));
      }
      {
        current_statement__ = 23;
        if (stan::math::logical_eq(estimate_mu, 1)) {
          current_statement__ = 22;
          lp_accum__.add(set_prior(
                           stan::model::rvalue(mu_est, "mu_est",
                             stan::model::index_uni(1)), prior_type_mu,
                           prior_parameters_mu, bounds_type_mu, bounds_mu,
                           pstream__));
        }
        current_statement__ = 25;
        if (stan::math::logical_eq(estimate_sigma, 1)) {
          current_statement__ = 24;
          lp_accum__.add(set_prior(
                           stan::model::rvalue(sigma_est, "sigma_est",
                             stan::model::index_uni(1)), prior_type_sigma,
                           prior_parameters_sigma, bounds_type_sigma,
                           bounds_sigma, pstream__));
        }
        current_statement__ = 27;
        if (stan::math::logical_eq(estimate_nu, 1)) {
          current_statement__ = 26;
          lp_accum__.add(set_prior(
                           stan::model::rvalue(nu_est, "nu_est",
                             stan::model::index_uni(1)), prior_type_nu,
                           prior_parameters_nu, bounds_type_nu, bounds_nu,
                           pstream__));
        }
        current_statement__ = 29;
        if (stan::math::logical_eq(sample_priors, 0)) {
          current_statement__ = 28;
          lp_accum__.add(stan::math::student_t_lpdf<false>(x, nu, mu, scale));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_t_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<double> mu_est =
        std::vector<double>(estimate_mu,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      mu_est = in__.template read_constrain_lub<
                 std::vector<local_scalar_t__>,
                 jacobian__>(coefs_lb(bounds_type_mu, bounds_mu, pstream__),
                 coefs_ub(bounds_type_mu, bounds_mu, pstream__), lp__,
                 estimate_mu);
      std::vector<double> sigma_est =
        std::vector<double>(estimate_sigma,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      sigma_est = in__.template read_constrain_lub<
                    std::vector<local_scalar_t__>,
                    jacobian__>(coefs_lb(bounds_type_sigma, bounds_sigma,
                                  pstream__),
                    coefs_ub(bounds_type_sigma, bounds_sigma, pstream__),
                    lp__, estimate_sigma);
      std::vector<double> nu_est =
        std::vector<double>(estimate_nu,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      nu_est = in__.template read_constrain_lub<
                 std::vector<local_scalar_t__>,
                 jacobian__>(coefs_lb(bounds_type_nu, bounds_nu, pstream__),
                 coefs_ub(bounds_type_nu, bounds_nu, pstream__), lp__,
                 estimate_nu);
      double mu = std::numeric_limits<double>::quiet_NaN();
      double scale = std::numeric_limits<double>::quiet_NaN();
      double nu = std::numeric_limits<double>::quiet_NaN();
      out__.write(mu_est);
      out__.write(sigma_est);
      out__.write(nu_est);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 11;
      if (stan::math::logical_eq(estimate_nu, 1)) {
        current_statement__ = 9;
        nu = (stan::model::rvalue(nu_est, "nu_est", stan::model::index_uni(1))
          + 2);
      } else {
        current_statement__ = 7;
        nu = stan::model::rvalue(fixed_nu, "fixed_nu",
               stan::model::index_uni(1));
      }
      current_statement__ = 16;
      if (stan::math::logical_eq(estimate_mu, 1)) {
        current_statement__ = 14;
        mu = stan::model::rvalue(mu_est, "mu_est", stan::model::index_uni(1));
      } else {
        current_statement__ = 12;
        mu = stan::model::rvalue(fixed_mu, "fixed_mu",
               stan::model::index_uni(1));
      }
      current_statement__ = 21;
      if (stan::math::logical_eq(estimate_sigma, 1)) {
        current_statement__ = 19;
        scale = (stan::model::rvalue(sigma_est, "sigma_est",
                   stan::model::index_uni(1))
          / stan::math::sqrt((nu / (nu - 2.0))));
      } else {
        current_statement__ = 17;
        scale = (stan::model::rvalue(fixed_sigma, "fixed_sigma",
                   stan::model::index_uni(1))
          / stan::math::sqrt((nu / (nu - 2.0))));
      }
      if (emit_transformed_parameters__) {
        out__.write(mu);
        out__.write(scale);
        out__.write(nu);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> mu_est =
        std::vector<local_scalar_t__>(estimate_mu, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(mu_est,
        in__.read<std::vector<local_scalar_t__>>(estimate_mu),
        "assigning variable mu_est");
      out__.write_free_lub(coefs_lb(bounds_type_mu, bounds_mu, pstream__),
        coefs_ub(bounds_type_mu, bounds_mu, pstream__), mu_est);
      std::vector<local_scalar_t__> sigma_est =
        std::vector<local_scalar_t__>(estimate_sigma, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(sigma_est,
        in__.read<std::vector<local_scalar_t__>>(estimate_sigma),
        "assigning variable sigma_est");
      out__.write_free_lub(coefs_lb(bounds_type_sigma, bounds_sigma,
                             pstream__),
        coefs_ub(bounds_type_sigma, bounds_sigma, pstream__), sigma_est);
      std::vector<local_scalar_t__> nu_est =
        std::vector<local_scalar_t__>(estimate_nu, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(nu_est,
        in__.read<std::vector<local_scalar_t__>>(estimate_nu),
        "assigning variable nu_est");
      out__.write_free_lub(coefs_lb(bounds_type_nu, bounds_nu, pstream__),
        coefs_ub(bounds_type_nu, bounds_nu, pstream__), nu_est);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu_est", "double",
        std::vector<size_t>{static_cast<size_t>(estimate_mu)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma_est",
        "double", std::vector<size_t>{static_cast<size_t>(estimate_sigma)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "nu_est", "double",
        std::vector<size_t>{static_cast<size_t>(estimate_nu)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> mu_est =
        std::vector<local_scalar_t__>(estimate_mu, DUMMY_VAR__);
      current_statement__ = 1;
      mu_est = context__.vals_r("mu_est");
      out__.write_free_lub(coefs_lb(bounds_type_mu, bounds_mu, pstream__),
        coefs_ub(bounds_type_mu, bounds_mu, pstream__), mu_est);
      std::vector<local_scalar_t__> sigma_est =
        std::vector<local_scalar_t__>(estimate_sigma, DUMMY_VAR__);
      current_statement__ = 2;
      sigma_est = context__.vals_r("sigma_est");
      out__.write_free_lub(coefs_lb(bounds_type_sigma, bounds_sigma,
                             pstream__),
        coefs_ub(bounds_type_sigma, bounds_sigma, pstream__), sigma_est);
      std::vector<local_scalar_t__> nu_est =
        std::vector<local_scalar_t__>(estimate_nu, DUMMY_VAR__);
      current_statement__ = 3;
      nu_est = context__.vals_r("nu_est");
      out__.write_free_lub(coefs_lb(bounds_type_nu, bounds_nu, pstream__),
        coefs_ub(bounds_type_nu, bounds_nu, pstream__), nu_est);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu_est", "sigma_est", "nu_est"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"mu", "scale", "nu"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    estimate_mu)},
                std::vector<size_t>{static_cast<size_t>(estimate_sigma)},
                std::vector<size_t>{static_cast<size_t>(estimate_nu)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= estimate_mu; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu_est" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= estimate_sigma; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_est" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= estimate_nu; ++sym1__) {
      param_names__.emplace_back(std::string() + "nu_est" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "mu");
      param_names__.emplace_back(std::string() + "scale");
      param_names__.emplace_back(std::string() + "nu");
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= estimate_mu; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu_est" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= estimate_sigma; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_est" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= estimate_nu; ++sym1__) {
      param_names__.emplace_back(std::string() + "nu_est" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "mu");
      param_names__.emplace_back(std::string() + "scale");
      param_names__.emplace_back(std::string() + "nu");
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu_est\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(estimate_mu) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"sigma_est\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(estimate_sigma) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"nu_est\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(estimate_nu) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"scale\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu_est\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(estimate_mu) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"sigma_est\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(estimate_sigma) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"nu_est\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(estimate_nu) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"scale\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((estimate_mu + estimate_sigma) +
      estimate_nu);
    const size_t num_transformed = emit_transformed_parameters * (((1 + 1) +
      1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((estimate_mu + estimate_sigma) +
      estimate_nu);
    const size_t num_transformed = emit_transformed_parameters * (((1 + 1) +
      1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_t_namespace::model_t;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_t_namespace::profiles__;
}
#endif
#endif
