// Generated by rstantools.  Do not edit by hand.

/*
    qc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    qc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with qc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_t_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 177> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 208, column 2 to column 112)",
  " (in 'string', line 209, column 2 to column 115)",
  " (in 'string', line 210, column 2 to column 114)",
  " (in 'string', line 213, column 2 to column 24)",
  " (in 'string', line 214, column 2 to column 45)",
  " (in 'string', line 218, column 2 to column 105)",
  " (in 'string', line 219, column 2 to column 108)",
  " (in 'string', line 220, column 2 to column 105)",
  " (in 'string', line 222, column 2 to column 46)",
  " (in 'string', line 189, column 2 to column 17)",
  " (in 'string', line 191, column 9 to column 10)",
  " (in 'string', line 191, column 2 to column 14)",
  " (in 'string', line 193, column 2 to column 22)",
  " (in 'string', line 194, column 2 to column 25)",
  " (in 'string', line 195, column 2 to column 22)",
  " (in 'string', line 196, column 2 to column 30)",
  " (in 'string', line 197, column 2 to column 33)",
  " (in 'string', line 198, column 2 to column 30)",
  " (in 'string', line 200, column 2 to column 32)",
  " (in 'string', line 201, column 2 to column 35)",
  " (in 'string', line 202, column 2 to column 32)",
  " (in 'string', line 203, column 2 to column 20)",
  " (in 'string', line 204, column 2 to column 23)",
  " (in 'string', line 205, column 2 to column 20)",
  " (in 'string', line 6, column 4 to column 13)",
  " (in 'string', line 5, column 32 to line 7, column 3)",
  " (in 'string', line 9, column 4 to column 24)",
  " (in 'string', line 8, column 38 to line 10, column 3)",
  " (in 'string', line 14, column 4 to column 13)",
  " (in 'string', line 15, column 4 to column 15)",
  " (in 'string', line 16, column 4 to column 12)",
  " (in 'string', line 20, column 6 to column 24)",
  " (in 'string', line 21, column 6 to column 26)",
  " (in 'string', line 19, column 11 to line 22, column 5)",
  " (in 'string', line 18, column 6 to column 33)",
  " (in 'string', line 17, column 36 to line 19, column 5)",
  " (in 'string', line 17, column 4 to line 22, column 5)",
  " (in 'string', line 26, column 6 to column 17)",
  " (in 'string', line 24, column 6 to column 31)",
  " (in 'string', line 23, column 4 to line 26, column 17)",
  " (in 'string', line 27, column 4 to column 14)",
  " (in 'string', line 13, column 54 to line 28, column 3)",
  " (in 'string', line 30, column 4 to column 13)",
  " (in 'string', line 31, column 4 to column 15)",
  " (in 'string', line 32, column 4 to column 12)",
  " (in 'string', line 36, column 6 to column 24)",
  " (in 'string', line 37, column 6 to column 26)",
  " (in 'string', line 35, column 11 to line 38, column 5)",
  " (in 'string', line 34, column 6 to column 33)",
  " (in 'string', line 33, column 36 to line 35, column 5)",
  " (in 'string', line 33, column 4 to line 38, column 5)",
  " (in 'string', line 42, column 6 to column 17)",
  " (in 'string', line 40, column 6 to column 31)",
  " (in 'string', line 39, column 4 to line 42, column 17)",
  " (in 'string', line 43, column 4 to column 14)",
  " (in 'string', line 29, column 54 to line 44, column 3)",
  " (in 'string', line 49, column 4 to column 12)",
  " (in 'string', line 53, column 6 to column 23)",
  " (in 'string', line 51, column 6 to column 31)",
  " (in 'string', line 50, column 4 to line 53, column 23)",
  " (in 'string', line 54, column 4 to column 14)",
  " (in 'string', line 48, column 46 to line 55, column 3)",
  " (in 'string', line 57, column 4 to column 12)",
  " (in 'string', line 61, column 6 to column 23)",
  " (in 'string', line 59, column 6 to column 31)",
  " (in 'string', line 58, column 4 to line 61, column 23)",
  " (in 'string', line 62, column 4 to column 14)",
  " (in 'string', line 56, column 46 to line 63, column 3)",
  " (in 'string', line 78, column 4 to column 12)",
  " (in 'string', line 181, column 6 to column 42)",
  " (in 'string', line 180, column 30 to line 182, column 5)",
  " (in 'string', line 180, column 10 to line 182, column 5)",
  " (in 'string', line 179, column 6 to column 39)",
  " (in 'string', line 178, column 30 to line 180, column 5)",
  " (in 'string', line 178, column 10 to line 182, column 5)",
  " (in 'string', line 167, column 6 to column 61)",
  " (in 'string', line 176, column 8 to column 65)",
  " (in 'string', line 175, column 35 to line 177, column 7)",
  " (in 'string', line 175, column 12 to line 177, column 7)",
  " (in 'string', line 174, column 8 to column 65)",
  " (in 'string', line 173, column 35 to line 175, column 7)",
  " (in 'string', line 173, column 12 to line 177, column 7)",
  " (in 'string', line 169, column 8 to line 172, column 10)",
  " (in 'string', line 168, column 52 to line 173, column 7)",
  " (in 'string', line 168, column 6 to line 177, column 7)",
  " (in 'string', line 166, column 29 to line 178, column 5)",
  " (in 'string', line 166, column 10 to line 182, column 5)",
  " (in 'string', line 155, column 6 to column 75)",
  " (in 'string', line 164, column 8 to column 79)",
  " (in 'string', line 163, column 35 to line 165, column 7)",
  " (in 'string', line 163, column 12 to line 165, column 7)",
  " (in 'string', line 162, column 8 to column 79)",
  " (in 'string', line 161, column 35 to line 163, column 7)",
  " (in 'string', line 161, column 12 to line 165, column 7)",
  " (in 'string', line 157, column 8 to line 160, column 10)",
  " (in 'string', line 156, column 52 to line 161, column 7)",
  " (in 'string', line 156, column 6 to line 165, column 7)",
  " (in 'string', line 154, column 29 to line 166, column 5)",
  " (in 'string', line 154, column 10 to line 182, column 5)",
  " (in 'string', line 153, column 6 to column 78)",
  " (in 'string', line 152, column 29 to line 154, column 5)",
  " (in 'string', line 152, column 10 to line 182, column 5)",
  " (in 'string', line 141, column 6 to column 80)",
  " (in 'string', line 150, column 8 to column 84)",
  " (in 'string', line 149, column 35 to line 151, column 7)",
  " (in 'string', line 149, column 12 to line 151, column 7)",
  " (in 'string', line 148, column 8 to column 84)",
  " (in 'string', line 147, column 35 to line 149, column 7)",
  " (in 'string', line 147, column 12 to line 151, column 7)",
  " (in 'string', line 143, column 8 to line 146, column 10)",
  " (in 'string', line 142, column 52 to line 147, column 7)",
  " (in 'string', line 142, column 6 to line 151, column 7)",
  " (in 'string', line 140, column 29 to line 152, column 5)",
  " (in 'string', line 140, column 10 to line 182, column 5)",
  " (in 'string', line 129, column 6 to column 76)",
  " (in 'string', line 138, column 8 to column 80)",
  " (in 'string', line 137, column 35 to line 139, column 7)",
  " (in 'string', line 137, column 12 to line 139, column 7)",
  " (in 'string', line 136, column 8 to column 80)",
  " (in 'string', line 135, column 35 to line 137, column 7)",
  " (in 'string', line 135, column 12 to line 139, column 7)",
  " (in 'string', line 131, column 8 to line 134, column 10)",
  " (in 'string', line 130, column 52 to line 135, column 7)",
  " (in 'string', line 130, column 6 to line 139, column 7)",
  " (in 'string', line 128, column 29 to line 140, column 5)",
  " (in 'string', line 128, column 10 to line 182, column 5)",
  " (in 'string', line 117, column 6 to column 101)",
  " (in 'string', line 126, column 8 to column 105)",
  " (in 'string', line 125, column 35 to line 127, column 7)",
  " (in 'string', line 125, column 12 to line 127, column 7)",
  " (in 'string', line 124, column 8 to column 105)",
  " (in 'string', line 123, column 35 to line 125, column 7)",
  " (in 'string', line 123, column 12 to line 127, column 7)",
  " (in 'string', line 119, column 8 to line 122, column 10)",
  " (in 'string', line 118, column 52 to line 123, column 7)",
  " (in 'string', line 118, column 6 to line 127, column 7)",
  " (in 'string', line 116, column 29 to line 128, column 5)",
  " (in 'string', line 116, column 10 to line 182, column 5)",
  " (in 'string', line 105, column 6 to column 77)",
  " (in 'string', line 114, column 8 to column 81)",
  " (in 'string', line 113, column 35 to line 115, column 7)",
  " (in 'string', line 113, column 12 to line 115, column 7)",
  " (in 'string', line 112, column 8 to column 81)",
  " (in 'string', line 111, column 35 to line 113, column 7)",
  " (in 'string', line 111, column 12 to line 115, column 7)",
  " (in 'string', line 107, column 8 to line 110, column 10)",
  " (in 'string', line 106, column 52 to line 111, column 7)",
  " (in 'string', line 106, column 6 to line 115, column 7)",
  " (in 'string', line 104, column 29 to line 116, column 5)",
  " (in 'string', line 104, column 10 to line 182, column 5)",
  " (in 'string', line 93, column 6 to column 80)",
  " (in 'string', line 102, column 8 to column 84)",
  " (in 'string', line 101, column 35 to line 103, column 7)",
  " (in 'string', line 101, column 12 to line 103, column 7)",
  " (in 'string', line 100, column 8 to column 84)",
  " (in 'string', line 99, column 35 to line 101, column 7)",
  " (in 'string', line 99, column 12 to line 103, column 7)",
  " (in 'string', line 95, column 8 to line 98, column 10)",
  " (in 'string', line 94, column 52 to line 99, column 7)",
  " (in 'string', line 94, column 6 to line 103, column 7)",
  " (in 'string', line 92, column 29 to line 104, column 5)",
  " (in 'string', line 92, column 10 to line 182, column 5)",
  " (in 'string', line 81, column 6 to column 77)",
  " (in 'string', line 90, column 8 to column 81)",
  " (in 'string', line 89, column 35 to line 91, column 7)",
  " (in 'string', line 89, column 12 to line 91, column 7)",
  " (in 'string', line 88, column 8 to column 81)",
  " (in 'string', line 87, column 35 to line 89, column 7)",
  " (in 'string', line 87, column 12 to line 91, column 7)",
  " (in 'string', line 83, column 8 to line 86, column 10)",
  " (in 'string', line 82, column 52 to line 87, column 7)",
  " (in 'string', line 82, column 6 to line 91, column 7)",
  " (in 'string', line 80, column 23 to line 92, column 5)",
  " (in 'string', line 80, column 4 to line 182, column 5)",
  " (in 'string', line 184, column 4 to column 14)",
  " (in 'string', line 77, column 113 to line 185, column 3)"};
template <bool propto__, typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>* = nullptr>
stan::promote_args_t<T0__>
Jeffreys_mu_lpdf(const T0__& mu, std::ostream* pstream__);
template <bool propto__, typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>* = nullptr>
stan::promote_args_t<T0__>
Jeffreys_sigma_lpdf(const T0__& sigma, std::ostream* pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>>
coefs_lb(const std::vector<int>& type_in, const T1__& bound_in_arg__,
         std::ostream* pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>>
coefs_ub(const std::vector<int>& type_in, const T1__& bound_in_arg__,
         std::ostream* pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>>
data_lb(const int& is_trunc, const T1__& trunc_in_arg__, std::ostream*
        pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>>
data_ub(const int& is_trunc, const T1__& trunc_in_arg__, std::ostream*
        pstream__);
template <typename T0__, typename T2__, typename T4__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>>* = nullptr>
stan::promote_args_t<T0__, stan::base_type_t<T2__>, stan::base_type_t<T4__>>
set_prior(const T0__& parameter, const int& prior_type, const T2__&
          prior_parameters_arg__, const std::vector<int>& bounds_type,
          const T4__& bounds_arg__, std::ostream* pstream__);
template <bool propto__, typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>*>
stan::promote_args_t<T0__>
Jeffreys_mu_lpdf(const T0__& mu, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__>;
  int current_statement__ = 0;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 25;
    return 0;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <bool propto__, typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>*>
stan::promote_args_t<T0__>
Jeffreys_sigma_lpdf(const T0__& sigma, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__>;
  int current_statement__ = 0;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 27;
    return stan::math::log((1 / sigma));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T1__>>
coefs_lb(const std::vector<int>& type_in, const T1__& bound_in_arg__,
         std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& bound_in = stan::math::to_ref(bound_in_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int type = std::numeric_limits<int>::min();
    local_scalar_t__ bound = DUMMY_VAR__;
    local_scalar_t__ lb = DUMMY_VAR__;
    current_statement__ = 37;
    if (stan::math::logical_eq(stan::math::num_elements(type_in), 0)) {
      current_statement__ = 35;
      return stan::math::negative_infinity();
    } else {
      current_statement__ = 32;
      type = stan::model::rvalue(type_in, "type_in",
               stan::model::index_uni(1));
      current_statement__ = 33;
      bound = stan::model::rvalue(bound_in, "bound_in",
                stan::model::index_uni(1));
    }
    current_statement__ = 40;
    if (stan::math::logical_eq(type, 0)) {
      current_statement__ = 39;
      lb = stan::math::negative_infinity();
    } else {
      current_statement__ = 38;
      lb = bound;
    }
    current_statement__ = 41;
    return lb;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T1__>>
coefs_ub(const std::vector<int>& type_in, const T1__& bound_in_arg__,
         std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& bound_in = stan::math::to_ref(bound_in_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int type = std::numeric_limits<int>::min();
    local_scalar_t__ bound = DUMMY_VAR__;
    local_scalar_t__ lb = DUMMY_VAR__;
    current_statement__ = 51;
    if (stan::math::logical_eq(stan::math::num_elements(type_in), 0)) {
      current_statement__ = 49;
      return stan::math::positive_infinity();
    } else {
      current_statement__ = 46;
      type = stan::model::rvalue(type_in, "type_in",
               stan::model::index_uni(2));
      current_statement__ = 47;
      bound = stan::model::rvalue(bound_in, "bound_in",
                stan::model::index_uni(2));
    }
    current_statement__ = 54;
    if (stan::math::logical_eq(type, 0)) {
      current_statement__ = 53;
      lb = stan::math::positive_infinity();
    } else {
      current_statement__ = 52;
      lb = bound;
    }
    current_statement__ = 55;
    return lb;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T1__>>
data_lb(const int& is_trunc, const T1__& trunc_in_arg__, std::ostream*
        pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& trunc_in = stan::math::to_ref(trunc_in_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ lb = DUMMY_VAR__;
    current_statement__ = 60;
    if (stan::math::logical_eq(is_trunc, 0)) {
      current_statement__ = 59;
      lb = stan::math::negative_infinity();
    } else {
      current_statement__ = 58;
      lb = stan::model::rvalue(trunc_in, "trunc_in",
             stan::model::index_uni(1));
    }
    current_statement__ = 61;
    return lb;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T1__>>
data_ub(const int& is_trunc, const T1__& trunc_in_arg__, std::ostream*
        pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& trunc_in = stan::math::to_ref(trunc_in_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ ub = DUMMY_VAR__;
    current_statement__ = 66;
    if (stan::math::logical_eq(is_trunc, 0)) {
      current_statement__ = 65;
      ub = stan::math::positive_infinity();
    } else {
      current_statement__ = 64;
      ub = stan::model::rvalue(trunc_in, "trunc_in",
             stan::model::index_uni(2));
    }
    current_statement__ = 67;
    return ub;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T2__, typename T4__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>>*>
stan::promote_args_t<T0__, stan::base_type_t<T2__>, stan::base_type_t<T4__>>
set_prior(const T0__& parameter, const int& prior_type, const T2__&
          prior_parameters_arg__, const std::vector<int>& bounds_type,
          const T4__& bounds_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T4__>>;
  int current_statement__ = 0;
  const auto& prior_parameters = stan::math::to_ref(prior_parameters_arg__);
  const auto& bounds = stan::math::to_ref(bounds_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ ll = DUMMY_VAR__;
    current_statement__ = 174;
    if (stan::math::logical_eq(prior_type, 1)) {
      current_statement__ = 163;
      ll = stan::math::normal_lpdf<false>(parameter,
             stan::model::rvalue(prior_parameters, "prior_parameters",
               stan::model::index_uni(1)),
             stan::model::rvalue(prior_parameters, "prior_parameters",
               stan::model::index_uni(2)));
      current_statement__ = 172;
      if ((stan::math::primitive_value(
             stan::math::logical_neq(
               stan::model::rvalue(bounds_type, "bounds_type",
                 stan::model::index_uni(1)), 0))
          &&
          stan::math::primitive_value(
            stan::math::logical_neq(
              stan::model::rvalue(bounds_type, "bounds_type",
                stan::model::index_uni(2)), 0)))) {
        current_statement__ = 170;
        ll = (ll -
          stan::math::log_diff_exp(
            stan::math::normal_lcdf(
              stan::model::rvalue(bounds, "bounds", stan::model::index_uni(2)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(2))),
            stan::math::normal_lcdf(
              stan::model::rvalue(bounds, "bounds", stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(2)))));
      } else {
        current_statement__ = 169;
        if (stan::math::logical_neq(
              stan::model::rvalue(bounds_type, "bounds_type",
                stan::model::index_uni(1)), 0)) {
          current_statement__ = 167;
          ll = (ll -
            stan::math::normal_lccdf(
              stan::model::rvalue(bounds, "bounds", stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(1)),
              stan::model::rvalue(prior_parameters, "prior_parameters",
                stan::model::index_uni(2))));
        } else {
          current_statement__ = 166;
          if (stan::math::logical_neq(
                stan::model::rvalue(bounds_type, "bounds_type",
                  stan::model::index_uni(2)), 0)) {
            current_statement__ = 164;
            ll = (ll -
              stan::math::normal_lcdf(
                stan::model::rvalue(bounds, "bounds",
                  stan::model::index_uni(2)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(2))));
          }
        }
      }
    } else {
      current_statement__ = 162;
      if (stan::math::logical_eq(prior_type, 2)) {
        current_statement__ = 151;
        ll = stan::math::lognormal_lpdf<false>(parameter,
               stan::model::rvalue(prior_parameters, "prior_parameters",
                 stan::model::index_uni(1)),
               stan::model::rvalue(prior_parameters, "prior_parameters",
                 stan::model::index_uni(2)));
        current_statement__ = 160;
        if ((stan::math::primitive_value(
               stan::math::logical_neq(
                 stan::model::rvalue(bounds_type, "bounds_type",
                   stan::model::index_uni(1)), 0))
            &&
            stan::math::primitive_value(
              stan::math::logical_neq(
                stan::model::rvalue(bounds_type, "bounds_type",
                  stan::model::index_uni(2)), 0)))) {
          current_statement__ = 158;
          ll = (ll -
            stan::math::log_diff_exp(
              stan::math::lognormal_lcdf(
                stan::model::rvalue(bounds, "bounds",
                  stan::model::index_uni(2)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(2))),
              stan::math::lognormal_lcdf(
                stan::model::rvalue(bounds, "bounds",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(2)))));
        } else {
          current_statement__ = 157;
          if (stan::math::logical_neq(
                stan::model::rvalue(bounds_type, "bounds_type",
                  stan::model::index_uni(1)), 0)) {
            current_statement__ = 155;
            ll = (ll -
              stan::math::lognormal_lccdf(
                stan::model::rvalue(bounds, "bounds",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(1)),
                stan::model::rvalue(prior_parameters, "prior_parameters",
                  stan::model::index_uni(2))));
          } else {
            current_statement__ = 154;
            if (stan::math::logical_neq(
                  stan::model::rvalue(bounds_type, "bounds_type",
                    stan::model::index_uni(2)), 0)) {
              current_statement__ = 152;
              ll = (ll -
                stan::math::lognormal_lcdf(
                  stan::model::rvalue(bounds, "bounds",
                    stan::model::index_uni(2)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(2))));
            }
          }
        }
      } else {
        current_statement__ = 150;
        if (stan::math::logical_eq(prior_type, 3)) {
          current_statement__ = 139;
          ll = stan::math::cauchy_lpdf<false>(parameter,
                 stan::model::rvalue(prior_parameters, "prior_parameters",
                   stan::model::index_uni(1)),
                 stan::model::rvalue(prior_parameters, "prior_parameters",
                   stan::model::index_uni(2)));
          current_statement__ = 148;
          if ((stan::math::primitive_value(
                 stan::math::logical_neq(
                   stan::model::rvalue(bounds_type, "bounds_type",
                     stan::model::index_uni(1)), 0))
              &&
              stan::math::primitive_value(
                stan::math::logical_neq(
                  stan::model::rvalue(bounds_type, "bounds_type",
                    stan::model::index_uni(2)), 0)))) {
            current_statement__ = 146;
            ll = (ll -
              stan::math::log_diff_exp(
                stan::math::cauchy_lcdf(
                  stan::model::rvalue(bounds, "bounds",
                    stan::model::index_uni(2)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(2))),
                stan::math::cauchy_lcdf(
                  stan::model::rvalue(bounds, "bounds",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(2)))));
          } else {
            current_statement__ = 145;
            if (stan::math::logical_neq(
                  stan::model::rvalue(bounds_type, "bounds_type",
                    stan::model::index_uni(1)), 0)) {
              current_statement__ = 143;
              ll = (ll -
                stan::math::cauchy_lccdf(
                  stan::model::rvalue(bounds, "bounds",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(1)),
                  stan::model::rvalue(prior_parameters, "prior_parameters",
                    stan::model::index_uni(2))));
            } else {
              current_statement__ = 142;
              if (stan::math::logical_neq(
                    stan::model::rvalue(bounds_type, "bounds_type",
                      stan::model::index_uni(2)), 0)) {
                current_statement__ = 140;
                ll = (ll -
                  stan::math::cauchy_lcdf(
                    stan::model::rvalue(bounds, "bounds",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(2))));
              }
            }
          }
        } else {
          current_statement__ = 138;
          if (stan::math::logical_eq(prior_type, 4)) {
            current_statement__ = 127;
            ll = stan::math::student_t_lpdf<false>(parameter,
                   stan::model::rvalue(prior_parameters, "prior_parameters",
                     stan::model::index_uni(1)),
                   stan::model::rvalue(prior_parameters, "prior_parameters",
                     stan::model::index_uni(2)),
                   stan::model::rvalue(prior_parameters, "prior_parameters",
                     stan::model::index_uni(3)));
            current_statement__ = 136;
            if ((stan::math::primitive_value(
                   stan::math::logical_neq(
                     stan::model::rvalue(bounds_type, "bounds_type",
                       stan::model::index_uni(1)), 0))
                &&
                stan::math::primitive_value(
                  stan::math::logical_neq(
                    stan::model::rvalue(bounds_type, "bounds_type",
                      stan::model::index_uni(2)), 0)))) {
              current_statement__ = 134;
              ll = (ll -
                stan::math::log_diff_exp(
                  stan::math::student_t_lcdf(
                    stan::model::rvalue(bounds, "bounds",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(3))),
                  stan::math::student_t_lcdf(
                    stan::model::rvalue(bounds, "bounds",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(3)))));
            } else {
              current_statement__ = 133;
              if (stan::math::logical_neq(
                    stan::model::rvalue(bounds_type, "bounds_type",
                      stan::model::index_uni(1)), 0)) {
                current_statement__ = 131;
                ll = (ll -
                  stan::math::student_t_lccdf(
                    stan::model::rvalue(bounds, "bounds",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(1)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(2)),
                    stan::model::rvalue(prior_parameters, "prior_parameters",
                      stan::model::index_uni(3))));
              } else {
                current_statement__ = 130;
                if (stan::math::logical_neq(
                      stan::model::rvalue(bounds_type, "bounds_type",
                        stan::model::index_uni(2)), 0)) {
                  current_statement__ = 128;
                  ll = (ll -
                    stan::math::student_t_lcdf(
                      stan::model::rvalue(bounds, "bounds",
                        stan::model::index_uni(2)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(2)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(3))));
                }
              }
            }
          } else {
            current_statement__ = 126;
            if (stan::math::logical_eq(prior_type, 5)) {
              current_statement__ = 115;
              ll = stan::math::gamma_lpdf<false>(parameter,
                     stan::model::rvalue(prior_parameters,
                       "prior_parameters", stan::model::index_uni(1)),
                     stan::model::rvalue(prior_parameters,
                       "prior_parameters", stan::model::index_uni(2)));
              current_statement__ = 124;
              if ((stan::math::primitive_value(
                     stan::math::logical_neq(
                       stan::model::rvalue(bounds_type, "bounds_type",
                         stan::model::index_uni(1)), 0))
                  &&
                  stan::math::primitive_value(
                    stan::math::logical_neq(
                      stan::model::rvalue(bounds_type, "bounds_type",
                        stan::model::index_uni(2)), 0)))) {
                current_statement__ = 122;
                ll = (ll -
                  stan::math::log_diff_exp(
                    stan::math::gamma_lcdf(
                      stan::model::rvalue(bounds, "bounds",
                        stan::model::index_uni(2)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(2))),
                    stan::math::gamma_lcdf(
                      stan::model::rvalue(bounds, "bounds",
                        stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(2)))));
              } else {
                current_statement__ = 121;
                if (stan::math::logical_neq(
                      stan::model::rvalue(bounds_type, "bounds_type",
                        stan::model::index_uni(1)), 0)) {
                  current_statement__ = 119;
                  ll = (ll -
                    stan::math::gamma_lccdf(
                      stan::model::rvalue(bounds, "bounds",
                        stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(1)),
                      stan::model::rvalue(prior_parameters,
                        "prior_parameters", stan::model::index_uni(2))));
                } else {
                  current_statement__ = 118;
                  if (stan::math::logical_neq(
                        stan::model::rvalue(bounds_type, "bounds_type",
                          stan::model::index_uni(2)), 0)) {
                    current_statement__ = 116;
                    ll = (ll -
                      stan::math::gamma_lcdf(
                        stan::model::rvalue(bounds, "bounds",
                          stan::model::index_uni(2)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(2))));
                  }
                }
              }
            } else {
              current_statement__ = 114;
              if (stan::math::logical_eq(prior_type, 6)) {
                current_statement__ = 103;
                ll = stan::math::inv_gamma_lpdf<false>(parameter,
                       stan::model::rvalue(prior_parameters,
                         "prior_parameters", stan::model::index_uni(1)),
                       stan::model::rvalue(prior_parameters,
                         "prior_parameters", stan::model::index_uni(2)));
                current_statement__ = 112;
                if ((stan::math::primitive_value(
                       stan::math::logical_neq(
                         stan::model::rvalue(bounds_type, "bounds_type",
                           stan::model::index_uni(1)), 0))
                    &&
                    stan::math::primitive_value(
                      stan::math::logical_neq(
                        stan::model::rvalue(bounds_type, "bounds_type",
                          stan::model::index_uni(2)), 0)))) {
                  current_statement__ = 110;
                  ll = (ll -
                    stan::math::log_diff_exp(
                      stan::math::inv_gamma_lcdf(
                        stan::model::rvalue(bounds, "bounds",
                          stan::model::index_uni(2)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(2))),
                      stan::math::inv_gamma_lcdf(
                        stan::model::rvalue(bounds, "bounds",
                          stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(2)))));
                } else {
                  current_statement__ = 109;
                  if (stan::math::logical_neq(
                        stan::model::rvalue(bounds_type, "bounds_type",
                          stan::model::index_uni(1)), 0)) {
                    current_statement__ = 107;
                    ll = (ll -
                      stan::math::inv_gamma_lccdf(
                        stan::model::rvalue(bounds, "bounds",
                          stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(1)),
                        stan::model::rvalue(prior_parameters,
                          "prior_parameters", stan::model::index_uni(2))));
                  } else {
                    current_statement__ = 106;
                    if (stan::math::logical_neq(
                          stan::model::rvalue(bounds_type, "bounds_type",
                            stan::model::index_uni(2)), 0)) {
                      current_statement__ = 104;
                      ll = (ll -
                        stan::math::inv_gamma_lcdf(
                          stan::model::rvalue(bounds, "bounds",
                            stan::model::index_uni(2)),
                          stan::model::rvalue(prior_parameters,
                            "prior_parameters", stan::model::index_uni(1)),
                          stan::model::rvalue(prior_parameters,
                            "prior_parameters", stan::model::index_uni(2))));
                    }
                  }
                }
              } else {
                current_statement__ = 102;
                if (stan::math::logical_eq(prior_type, 7)) {
                  current_statement__ = 100;
                  ll = stan::math::uniform_lpdf<false>(parameter,
                         stan::model::rvalue(prior_parameters,
                           "prior_parameters", stan::model::index_uni(1)),
                         stan::model::rvalue(prior_parameters,
                           "prior_parameters", stan::model::index_uni(2)));
                } else {
                  current_statement__ = 99;
                  if (stan::math::logical_eq(prior_type, 8)) {
                    current_statement__ = 88;
                    ll = stan::math::beta_lpdf<false>(parameter,
                           stan::model::rvalue(prior_parameters,
                             "prior_parameters", stan::model::index_uni(1)),
                           stan::model::rvalue(prior_parameters,
                             "prior_parameters", stan::model::index_uni(2)));
                    current_statement__ = 97;
                    if ((stan::math::primitive_value(
                           stan::math::logical_neq(
                             stan::model::rvalue(bounds_type, "bounds_type",
                               stan::model::index_uni(1)), 0))
                        &&
                        stan::math::primitive_value(
                          stan::math::logical_neq(
                            stan::model::rvalue(bounds_type, "bounds_type",
                              stan::model::index_uni(2)), 0)))) {
                      current_statement__ = 95;
                      ll = (ll -
                        stan::math::log_diff_exp(
                          stan::math::beta_lcdf(
                            stan::model::rvalue(bounds, "bounds",
                              stan::model::index_uni(2)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(2))),
                          stan::math::beta_lcdf(
                            stan::model::rvalue(bounds, "bounds",
                              stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(2)))));
                    } else {
                      current_statement__ = 94;
                      if (stan::math::logical_neq(
                            stan::model::rvalue(bounds_type, "bounds_type",
                              stan::model::index_uni(1)), 0)) {
                        current_statement__ = 92;
                        ll = (ll -
                          stan::math::beta_lccdf(
                            stan::model::rvalue(bounds, "bounds",
                              stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(1)),
                            stan::model::rvalue(prior_parameters,
                              "prior_parameters", stan::model::index_uni(2))));
                      } else {
                        current_statement__ = 91;
                        if (stan::math::logical_neq(
                              stan::model::rvalue(bounds_type, "bounds_type",
                                stan::model::index_uni(2)), 0)) {
                          current_statement__ = 89;
                          ll = (ll -
                            stan::math::beta_lcdf(
                              stan::model::rvalue(bounds, "bounds",
                                stan::model::index_uni(2)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(1)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(2))));
                        }
                      }
                    }
                  } else {
                    current_statement__ = 87;
                    if (stan::math::logical_eq(prior_type, 9)) {
                      current_statement__ = 76;
                      ll = stan::math::exponential_lpdf<false>(parameter,
                             stan::model::rvalue(prior_parameters,
                               "prior_parameters", stan::model::index_uni(1)));
                      current_statement__ = 85;
                      if ((stan::math::primitive_value(
                             stan::math::logical_neq(
                               stan::model::rvalue(bounds_type,
                                 "bounds_type", stan::model::index_uni(1)), 0))
                          &&
                          stan::math::primitive_value(
                            stan::math::logical_neq(
                              stan::model::rvalue(bounds_type, "bounds_type",
                                stan::model::index_uni(2)), 0)))) {
                        current_statement__ = 83;
                        ll = (ll -
                          stan::math::log_diff_exp(
                            stan::math::exponential_lcdf(
                              stan::model::rvalue(bounds, "bounds",
                                stan::model::index_uni(2)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(1))),
                            stan::math::exponential_lcdf(
                              stan::model::rvalue(bounds, "bounds",
                                stan::model::index_uni(1)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(1)))));
                      } else {
                        current_statement__ = 82;
                        if (stan::math::logical_neq(
                              stan::model::rvalue(bounds_type, "bounds_type",
                                stan::model::index_uni(1)), 0)) {
                          current_statement__ = 80;
                          ll = (ll -
                            stan::math::exponential_lccdf(
                              stan::model::rvalue(bounds, "bounds",
                                stan::model::index_uni(1)),
                              stan::model::rvalue(prior_parameters,
                                "prior_parameters", stan::model::index_uni(1))));
                        } else {
                          current_statement__ = 79;
                          if (stan::math::logical_neq(
                                stan::model::rvalue(bounds_type,
                                  "bounds_type", stan::model::index_uni(2)),
                                0)) {
                            current_statement__ = 77;
                            ll = (ll -
                              stan::math::exponential_lcdf(
                                stan::model::rvalue(bounds, "bounds",
                                  stan::model::index_uni(2)),
                                stan::model::rvalue(prior_parameters,
                                  "prior_parameters",
                                  stan::model::index_uni(1))));
                          }
                        }
                      }
                    } else {
                      current_statement__ = 75;
                      if (stan::math::logical_eq(prior_type, 98)) {
                        current_statement__ = 73;
                        ll = Jeffreys_mu_lpdf<false>(parameter, pstream__);
                      } else {
                        current_statement__ = 72;
                        if (stan::math::logical_eq(prior_type, 99)) {
                          current_statement__ = 70;
                          ll = Jeffreys_sigma_lpdf<false>(parameter,
                                 pstream__);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    current_statement__ = 175;
    return ll;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_t final : public model_base_crtp<model_t> {
private:
  int N;
  Eigen::Matrix<double,-1,1> x_data__;
  Eigen::Matrix<double,-1,1> bounds_mu_data__;
  Eigen::Matrix<double,-1,1> bounds_sigma_data__;
  Eigen::Matrix<double,-1,1> bounds_nu_data__;
  std::vector<int> bounds_type_mu;
  std::vector<int> bounds_type_sigma;
  std::vector<int> bounds_type_nu;
  Eigen::Matrix<double,-1,1> prior_parameters_mu_data__;
  Eigen::Matrix<double,-1,1> prior_parameters_sigma_data__;
  Eigen::Matrix<double,-1,1> prior_parameters_nu_data__;
  int prior_type_mu;
  int prior_type_sigma;
  int prior_type_nu;
  Eigen::Map<Eigen::Matrix<double,-1,1>> x{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> bounds_mu{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> bounds_sigma{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> bounds_nu{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_parameters_mu{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_parameters_sigma{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_parameters_nu{nullptr, 0};
public:
  ~model_t() {}
  model_t(stan::io::var_context& context__, unsigned int random_seed__ = 0,
          std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ = "model_t_namespace::model_t";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 10;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 10;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 11;
      stan::math::validate_non_negative_index("x", "N", N);
      current_statement__ = 12;
      context__.validate_dims("data initialization", "x", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      x_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&x) Eigen::Map<Eigen::Matrix<double,-1,1>>(x_data__.data(), N);
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 12;
        x_flat__ = context__.vals_r("x");
        current_statement__ = 12;
        pos__ = 1;
        current_statement__ = 12;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 12;
          stan::model::assign(x, x_flat__[(pos__ - 1)],
            "assigning variable x", stan::model::index_uni(sym1__));
          current_statement__ = 12;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 13;
      context__.validate_dims("data initialization", "bounds_mu", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      bounds_mu_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                           std::numeric_limits<double>::quiet_NaN());
      new (&bounds_mu)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(bounds_mu_data__.data(), 2);
      {
        std::vector<local_scalar_t__> bounds_mu_flat__;
        current_statement__ = 13;
        bounds_mu_flat__ = context__.vals_r("bounds_mu");
        current_statement__ = 13;
        pos__ = 1;
        current_statement__ = 13;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 13;
          stan::model::assign(bounds_mu, bounds_mu_flat__[(pos__ - 1)],
            "assigning variable bounds_mu", stan::model::index_uni(sym1__));
          current_statement__ = 13;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 14;
      context__.validate_dims("data initialization", "bounds_sigma",
        "double", std::vector<size_t>{static_cast<size_t>(2)});
      bounds_sigma_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                              std::numeric_limits<double>::quiet_NaN());
      new (&bounds_sigma)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(bounds_sigma_data__.data(), 2);
      {
        std::vector<local_scalar_t__> bounds_sigma_flat__;
        current_statement__ = 14;
        bounds_sigma_flat__ = context__.vals_r("bounds_sigma");
        current_statement__ = 14;
        pos__ = 1;
        current_statement__ = 14;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 14;
          stan::model::assign(bounds_sigma, bounds_sigma_flat__[(pos__ - 1)],
            "assigning variable bounds_sigma", stan::model::index_uni(sym1__));
          current_statement__ = 14;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 15;
      context__.validate_dims("data initialization", "bounds_nu", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      bounds_nu_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                           std::numeric_limits<double>::quiet_NaN());
      new (&bounds_nu)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(bounds_nu_data__.data(), 2);
      {
        std::vector<local_scalar_t__> bounds_nu_flat__;
        current_statement__ = 15;
        bounds_nu_flat__ = context__.vals_r("bounds_nu");
        current_statement__ = 15;
        pos__ = 1;
        current_statement__ = 15;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 15;
          stan::model::assign(bounds_nu, bounds_nu_flat__[(pos__ - 1)],
            "assigning variable bounds_nu", stan::model::index_uni(sym1__));
          current_statement__ = 15;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 16;
      context__.validate_dims("data initialization", "bounds_type_mu", "int",
        std::vector<size_t>{static_cast<size_t>(2)});
      bounds_type_mu = std::vector<int>(2, std::numeric_limits<int>::min());
      current_statement__ = 16;
      bounds_type_mu = context__.vals_i("bounds_type_mu");
      current_statement__ = 17;
      context__.validate_dims("data initialization", "bounds_type_sigma",
        "int", std::vector<size_t>{static_cast<size_t>(2)});
      bounds_type_sigma = std::vector<int>(2,
                            std::numeric_limits<int>::min());
      current_statement__ = 17;
      bounds_type_sigma = context__.vals_i("bounds_type_sigma");
      current_statement__ = 18;
      context__.validate_dims("data initialization", "bounds_type_nu", "int",
        std::vector<size_t>{static_cast<size_t>(2)});
      bounds_type_nu = std::vector<int>(2, std::numeric_limits<int>::min());
      current_statement__ = 18;
      bounds_type_nu = context__.vals_i("bounds_type_nu");
      current_statement__ = 19;
      context__.validate_dims("data initialization", "prior_parameters_mu",
        "double", std::vector<size_t>{static_cast<size_t>(3)});
      prior_parameters_mu_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                                     std::numeric_limits<double>::quiet_NaN());
      new (&prior_parameters_mu)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_parameters_mu_data__.data(),
        3);
      {
        std::vector<local_scalar_t__> prior_parameters_mu_flat__;
        current_statement__ = 19;
        prior_parameters_mu_flat__ = context__.vals_r("prior_parameters_mu");
        current_statement__ = 19;
        pos__ = 1;
        current_statement__ = 19;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          current_statement__ = 19;
          stan::model::assign(prior_parameters_mu,
            prior_parameters_mu_flat__[(pos__ - 1)],
            "assigning variable prior_parameters_mu",
            stan::model::index_uni(sym1__));
          current_statement__ = 19;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 20;
      context__.validate_dims("data initialization",
        "prior_parameters_sigma", "double",
        std::vector<size_t>{static_cast<size_t>(3)});
      prior_parameters_sigma_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                                        std::numeric_limits<double>::quiet_NaN(
                                          ));
      new (&prior_parameters_sigma)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_parameters_sigma_data__.data(),
        3);
      {
        std::vector<local_scalar_t__> prior_parameters_sigma_flat__;
        current_statement__ = 20;
        prior_parameters_sigma_flat__ = context__.vals_r("prior_parameters_sigma");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          current_statement__ = 20;
          stan::model::assign(prior_parameters_sigma,
            prior_parameters_sigma_flat__[(pos__ - 1)],
            "assigning variable prior_parameters_sigma",
            stan::model::index_uni(sym1__));
          current_statement__ = 20;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      context__.validate_dims("data initialization", "prior_parameters_nu",
        "double", std::vector<size_t>{static_cast<size_t>(3)});
      prior_parameters_nu_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                                     std::numeric_limits<double>::quiet_NaN());
      new (&prior_parameters_nu)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_parameters_nu_data__.data(),
        3);
      {
        std::vector<local_scalar_t__> prior_parameters_nu_flat__;
        current_statement__ = 21;
        prior_parameters_nu_flat__ = context__.vals_r("prior_parameters_nu");
        current_statement__ = 21;
        pos__ = 1;
        current_statement__ = 21;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          current_statement__ = 21;
          stan::model::assign(prior_parameters_nu,
            prior_parameters_nu_flat__[(pos__ - 1)],
            "assigning variable prior_parameters_nu",
            stan::model::index_uni(sym1__));
          current_statement__ = 21;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 22;
      context__.validate_dims("data initialization", "prior_type_mu", "int",
        std::vector<size_t>{});
      prior_type_mu = std::numeric_limits<int>::min();
      current_statement__ = 22;
      prior_type_mu = context__.vals_i("prior_type_mu")[(1 - 1)];
      current_statement__ = 23;
      context__.validate_dims("data initialization", "prior_type_sigma",
        "int", std::vector<size_t>{});
      prior_type_sigma = std::numeric_limits<int>::min();
      current_statement__ = 23;
      prior_type_sigma = context__.vals_i("prior_type_sigma")[(1 - 1)];
      current_statement__ = 24;
      context__.validate_dims("data initialization", "prior_type_nu", "int",
        std::vector<size_t>{});
      prior_type_nu = std::numeric_limits<int>::min();
      current_statement__ = 24;
      prior_type_nu = context__.vals_i("prior_type_nu")[(1 - 1)];
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_t";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ = "model_t_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.template read_constrain_lub<local_scalar_t__,
             jacobian__>(coefs_lb(bounds_type_mu, bounds_mu, pstream__),
             coefs_ub(bounds_type_mu, bounds_mu, pstream__), lp__);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(coefs_lb(bounds_type_sigma, bounds_sigma,
                              pstream__),
                coefs_ub(bounds_type_sigma, bounds_sigma, pstream__), lp__);
      local_scalar_t__ nu_p = DUMMY_VAR__;
      current_statement__ = 3;
      nu_p = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(coefs_lb(bounds_type_nu, bounds_nu, pstream__),
               coefs_ub(bounds_type_nu, bounds_nu, pstream__), lp__);
      local_scalar_t__ nu = DUMMY_VAR__;
      current_statement__ = 4;
      nu = (nu_p + 2);
      local_scalar_t__ scale = DUMMY_VAR__;
      current_statement__ = 5;
      scale = (sigma / stan::math::sqrt((nu / (nu - 2.0))));
      {
        current_statement__ = 6;
        lp_accum__.add(set_prior(mu, prior_type_mu, prior_parameters_mu,
                         bounds_type_mu, bounds_mu, pstream__));
        current_statement__ = 7;
        lp_accum__.add(set_prior(sigma, prior_type_sigma,
                         prior_parameters_sigma, bounds_type_sigma,
                         bounds_sigma, pstream__));
        current_statement__ = 8;
        lp_accum__.add(set_prior(nu_p, prior_type_nu, prior_parameters_nu,
                         bounds_type_nu, bounds_nu, pstream__));
        current_statement__ = 9;
        lp_accum__.add(stan::math::student_t_lpdf<false>(x, nu, mu, scale));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_t_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      mu = in__.template read_constrain_lub<local_scalar_t__,
             jacobian__>(coefs_lb(bounds_type_mu, bounds_mu, pstream__),
             coefs_ub(bounds_type_mu, bounds_mu, pstream__), lp__);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(coefs_lb(bounds_type_sigma, bounds_sigma,
                              pstream__),
                coefs_ub(bounds_type_sigma, bounds_sigma, pstream__), lp__);
      double nu_p = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      nu_p = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(coefs_lb(bounds_type_nu, bounds_nu, pstream__),
               coefs_ub(bounds_type_nu, bounds_nu, pstream__), lp__);
      double nu = std::numeric_limits<double>::quiet_NaN();
      double scale = std::numeric_limits<double>::quiet_NaN();
      out__.write(mu);
      out__.write(sigma);
      out__.write(nu_p);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 4;
      nu = (nu_p + 2);
      current_statement__ = 5;
      scale = (sigma / stan::math::sqrt((nu / (nu - 2.0))));
      if (emit_transformed_parameters__) {
        out__.write(nu);
        out__.write(scale);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.read<local_scalar_t__>();
      out__.write_free_lub(coefs_lb(bounds_type_mu, bounds_mu, pstream__),
        coefs_ub(bounds_type_mu, bounds_mu, pstream__), mu);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lub(coefs_lb(bounds_type_sigma, bounds_sigma,
                             pstream__),
        coefs_ub(bounds_type_sigma, bounds_sigma, pstream__), sigma);
      local_scalar_t__ nu_p = DUMMY_VAR__;
      current_statement__ = 3;
      nu_p = in__.read<local_scalar_t__>();
      out__.write_free_lub(coefs_lb(bounds_type_nu, bounds_nu, pstream__),
        coefs_ub(bounds_type_nu, bounds_nu, pstream__), nu_p);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "nu_p", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = context__.vals_r("mu")[(1 - 1)];
      out__.write_free_lub(coefs_lb(bounds_type_mu, bounds_mu, pstream__),
        coefs_ub(bounds_type_mu, bounds_mu, pstream__), mu);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lub(coefs_lb(bounds_type_sigma, bounds_sigma,
                             pstream__),
        coefs_ub(bounds_type_sigma, bounds_sigma, pstream__), sigma);
      local_scalar_t__ nu_p = DUMMY_VAR__;
      current_statement__ = 3;
      nu_p = context__.vals_r("nu_p")[(1 - 1)];
      out__.write_free_lub(coefs_lb(bounds_type_nu, bounds_nu, pstream__),
        coefs_ub(bounds_type_nu, bounds_nu, pstream__), nu_p);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu", "sigma", "nu_p"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"nu", "scale"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "nu_p");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "nu");
      param_names__.emplace_back(std::string() + "scale");
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "nu_p");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "nu");
      param_names__.emplace_back(std::string() + "scale");
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu_p\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"scale\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu_p\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"scale\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((1 + 1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((1 + 1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_t_namespace::model_t;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_t_namespace::profiles__;
}
#endif
#endif
